"""
test_migrate_source.py — Tests for the ``migrate-source`` subcommand.

``import-legacy`` generates a ``legacy_migration.sed`` that converts
$VAR / ${VAR} / &&VAR&& markers to {{TOKEN}} form. This module verifies
that ``source_migrator`` correctly applies those rules to a source
tree without requiring the ``sed`` binary — the whole point is that
it works on Windows.

Three layers:

  1. ``parse_migration_sed`` — sed parser (valid rules, skipped lines).
  2. ``migrate_source_directory`` — file application (changes made,
     dry-run, recursion, binary-safe).
  3. CLI via ``td_release_packager.cli.main()`` — subcommand wiring.
"""

from __future__ import annotations

import sys

import pytest

from td_release_packager.source_migrator import (
    MigrationRule,
    apply_migration_rules_to_text,
    migrate_source_directory,
    parse_migration_sed,
)


# ---------------------------------------------------------------
# parse_migration_sed
# ---------------------------------------------------------------


class TestParseMigrationSed:
    def test_parses_basic_rule(self):
        rules, skipped = parse_migration_sed("s/$OPR_M/{{OPR_M}}/g\n")
        assert len(rules) == 1
        assert rules[0].raw_lhs == "$OPR_M"
        assert rules[0].rhs == "{{OPR_M}}"
        assert rules[0].global_ is True
        assert skipped == []

    def test_comments_and_blanks_ignored(self):
        content = (
            "# generated by import-legacy\n\ns/$A/{{A}}/g\n  # comment\ns/$B/{{B}}/g\n"
        )
        rules, skipped = parse_migration_sed(content)
        assert len(rules) == 2
        assert skipped == []

    def test_multiple_syntaxes_parsed(self):
        content = "s/$VAR/{{VAR}}/g\ns/${VAR}/{{VAR}}/g\ns/&&VAR&&/{{VAR}}/g\n"
        rules, skipped = parse_migration_sed(content)
        assert len(rules) == 3

    def test_unrecognised_line_goes_to_skipped(self):
        content = "s/$A/{{A}}/g\nnot_a_sed_rule\n"
        rules, skipped = parse_migration_sed(content)
        assert len(rules) == 1
        assert "not_a_sed_rule" in skipped

    def test_escaped_slash_in_value(self):
        content = "s/$A/some\\/path/g\n"
        rules, skipped = parse_migration_sed(content)
        assert len(rules) == 1
        assert rules[0].rhs == "some/path"

    def test_empty_script_returns_no_rules(self):
        rules, skipped = parse_migration_sed("# nothing here\n")
        assert rules == []
        assert skipped == []


# ---------------------------------------------------------------
# migrate_source_directory
# ---------------------------------------------------------------


def _make_rules(*pairs):
    """Build a list of MigrationRule from (pattern, replacement) pairs."""
    import re

    rules = []
    for raw_lhs, rhs in pairs:
        rules.append(
            MigrationRule(
                raw_lhs=raw_lhs,
                lhs=re.compile(re.escape(raw_lhs)),
                rhs=rhs,
                global_=True,
            )
        )
    return rules


class TestMigrateSourceDirectory:
    def test_replaces_placeholder_in_db_file(self, tmp_path):
        (tmp_path / "x.db").write_text(
            "CREATE DATABASE $OPR_M FROM $OPR_NODE\nAS PERM=0;\n",
            encoding="utf-8",
        )
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"), ("$OPR_NODE", "{{OPR_NODE}}"))

        result = migrate_source_directory(str(tmp_path), rules)

        assert result.files_changed == 1
        content = (tmp_path / "x.db").read_text(encoding="utf-8")
        assert "{{OPR_M}}" in content
        assert "$OPR_M" not in content

    def test_dry_run_does_not_write(self, tmp_path):
        original = "CREATE DATABASE $OPR_M FROM $OPR_NODE;\n"
        (tmp_path / "x.db").write_text(original, encoding="utf-8")
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"))

        result = migrate_source_directory(str(tmp_path), rules, dry_run=True)

        assert result.dry_run is True
        assert result.files_changed == 1
        # File must be UNCHANGED in dry-run mode.
        assert (tmp_path / "x.db").read_text(encoding="utf-8") == original

    def test_unchanged_file_not_counted(self, tmp_path):
        (tmp_path / "clean.tbl").write_text(
            "CREATE TABLE {{T_DB}}.X (Id INT);", encoding="utf-8"
        )
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"))

        result = migrate_source_directory(str(tmp_path), rules)

        assert result.files_changed == 0
        assert result.files_scanned == 1

    def test_rule_hits_counted_correctly(self, tmp_path):
        (tmp_path / "a.db").write_text("$OPR_M $OPR_M $OPR_M", encoding="utf-8")
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"))

        result = migrate_source_directory(str(tmp_path), rules)

        assert result.rule_hits.get("$OPR_M") == 3

    def test_recursive_walk(self, tmp_path):
        sub = tmp_path / "sub" / "deep"
        sub.mkdir(parents=True)
        (sub / "x.db").write_text("$OPR_M", encoding="utf-8")
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"))

        result = migrate_source_directory(str(tmp_path), rules)

        assert result.files_changed == 1

    def test_bteq_leading_command_preserved(self, tmp_path):
        """The .IF ERRORCODE BTEQ line must survive unchanged."""
        original = (
            ".IF ERRORCODE <> 0 THEN .GOTO ERR\n\n"
            "CREATE DATABASE $OPR_M FROM $OPR_NODE\nAS PERM=0;\n"
        )
        (tmp_path / "x.db").write_text(original, encoding="utf-8")
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"), ("$OPR_NODE", "{{OPR_NODE}}"))

        migrate_source_directory(str(tmp_path), rules)

        result = (tmp_path / "x.db").read_text(encoding="utf-8")
        assert ".IF ERRORCODE <> 0 THEN .GOTO ERR" in result
        assert "{{OPR_M}}" in result
        assert "{{OPR_NODE}}" in result

    def test_multiple_syntaxes_all_converted(self, tmp_path):
        """$VAR, ${VAR} and &&VAR&& in the same file all get replaced."""
        (tmp_path / "x.db").write_text("$A ${B} &&C&&", encoding="utf-8")
        rules = _make_rules(("$A", "{{A}}"), ("${B}", "{{B}}"), ("&&C&&", "{{C}}"))
        migrate_source_directory(str(tmp_path), rules)
        content = (tmp_path / "x.db").read_text(encoding="utf-8")
        assert content == "{{A}} {{B}} {{C}}"

    def test_apply_rules_to_text_does_not_touch_files(self, tmp_path):
        """Harvest can normalise legacy markers in memory."""
        source = tmp_path / "x.db"
        original = "CREATE DATABASE $OPR_M FROM $OPR_NODE;\n"
        source.write_text(original, encoding="utf-8")
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"), ("$OPR_NODE", "{{OPR_NODE}}"))

        migrated, hits = apply_migration_rules_to_text(original, rules)

        assert migrated == "CREATE DATABASE {{OPR_M}} FROM {{OPR_NODE}};\n"
        assert hits == {"$OPR_M": 1, "$OPR_NODE": 1}
        assert source.read_text(encoding="utf-8") == original


# ---------------------------------------------------------------
# CLI subcommand wiring
# ---------------------------------------------------------------


class TestMigrateSourceCLI:
    def _invoke(self, argv):
        old = sys.argv
        sys.argv = ["td_release_packager"] + argv
        try:
            from td_release_packager.cli import main

            with pytest.raises(SystemExit) as ei:
                main()
            return int(ei.value.code) if ei.value.code is not None else 0
        finally:
            sys.argv = old

    def test_end_to_end_via_subcommand(self, tmp_path, capsys):
        src = tmp_path / "src"
        src.mkdir()
        (src / "x.db").write_text(
            "CREATE DATABASE $OPR_M FROM $OPR_NODE;\n", encoding="utf-8"
        )
        sed = tmp_path / "legacy_migration.sed"
        sed.write_text(
            "s/$OPR_M/{{OPR_M}}/g\ns/$OPR_NODE/{{OPR_NODE}}/g\n",
            encoding="utf-8",
        )

        rc = self._invoke(["migrate-source", "--sed", str(sed), "--source", str(src)])
        capsys.readouterr()

        assert rc == 0
        content = (src / "x.db").read_text(encoding="utf-8")
        assert "{{OPR_M}}" in content
        assert "$OPR_M" not in content

    def test_dry_run_via_subcommand(self, tmp_path, capsys):
        src = tmp_path / "src"
        src.mkdir()
        original = "CREATE DATABASE $OPR_M;\n"
        (src / "x.db").write_text(original, encoding="utf-8")
        sed = tmp_path / "legacy_migration.sed"
        sed.write_text("s/$OPR_M/{{OPR_M}}/g\n", encoding="utf-8")

        rc = self._invoke(
            [
                "migrate-source",
                "--sed",
                str(sed),
                "--source",
                str(src),
                "--dry-run",
            ]
        )
        capsys.readouterr()

        assert rc == 0
        # File unchanged in dry-run mode.
        assert (src / "x.db").read_text(encoding="utf-8") == original

    def test_missing_sed_returns_nonzero(self, tmp_path, capsys):
        rc = self._invoke(
            [
                "migrate-source",
                "--sed",
                str(tmp_path / "nope.sed"),
                "--source",
                str(tmp_path),
            ]
        )
        capsys.readouterr()
        assert rc == 1

    def test_missing_source_returns_nonzero(self, tmp_path, capsys):
        sed = tmp_path / "m.sed"
        sed.write_text("s/$A/{{A}}/g\n", encoding="utf-8")
        rc = self._invoke(
            [
                "migrate-source",
                "--sed",
                str(sed),
                "--source",
                str(tmp_path / "nope"),
            ]
        )
        capsys.readouterr()
        assert rc == 1
