"""
test_migrate_source.py — Tests for the ``migrate-source`` subcommand.

The canonical tokenisation config is ``config/tokenise.conf``. It
accepts literal ``s/LHS/RHS/g`` rules (what ``import-legacy``
generates) and full ``regex::PATTERN:=REPLACEMENT`` rules (hand-
authored, with ``$1..$9`` capture-group back-references). Both forms
coexist in the same file.

Three layers:

  1. ``parse_migration_sed`` — parser (valid rules, skipped lines).
  2. ``migrate_source_directory`` — file application (changes made,
     dry-run, recursion, binary-safe).
  3. CLI via ``td_release_packager.cli.main()`` — subcommand wiring.
"""

from __future__ import annotations

import sys

import pytest

from td_release_packager.source_migrator import (
    MigrationRule,
    apply_migration_rules_to_text,
    migrate_source_directory,
    parse_migration_sed,
)


# ---------------------------------------------------------------
# parse_migration_sed
# ---------------------------------------------------------------


class TestParseMigrationSed:
    def test_parses_basic_rule(self):
        rules, skipped = parse_migration_sed("s/$OPR_M/{{OPR_M}}/g\n")
        assert len(rules) == 1
        assert rules[0].raw_lhs == "$OPR_M"
        assert rules[0].rhs == "{{OPR_M}}"
        assert rules[0].global_ is True
        assert skipped == []

    def test_comments_and_blanks_ignored(self):
        content = (
            "# generated by import-legacy\n\ns/$A/{{A}}/g\n  # comment\ns/$B/{{B}}/g\n"
        )
        rules, skipped = parse_migration_sed(content)
        assert len(rules) == 2
        assert skipped == []

    def test_multiple_syntaxes_parsed(self):
        content = "s/$VAR/{{VAR}}/g\ns/${VAR}/{{VAR}}/g\ns/&&VAR&&/{{VAR}}/g\n"
        rules, skipped = parse_migration_sed(content)
        assert len(rules) == 3

    def test_unrecognised_line_goes_to_skipped(self):
        content = "s/$A/{{A}}/g\nnot_a_sed_rule\n"
        rules, skipped = parse_migration_sed(content)
        assert len(rules) == 1
        assert "not_a_sed_rule" in skipped

    def test_escaped_slash_in_value(self):
        content = "s/$A/some\\/path/g\n"
        rules, skipped = parse_migration_sed(content)
        assert len(rules) == 1
        assert rules[0].rhs == "some/path"

    def test_empty_script_returns_no_rules(self):
        rules, skipped = parse_migration_sed("# nothing here\n")
        assert rules == []
        assert skipped == []


# ---------------------------------------------------------------
# Regex rule syntax  (issue #259)
# ---------------------------------------------------------------


class TestRegexRuleSyntax:
    def test_basic_regex_rule_parses(self):
        rules, skipped = parse_migration_sed("regex::foo:=bar\n")
        assert len(rules) == 1
        assert rules[0].is_regex is True
        assert rules[0].raw_lhs == "foo"
        assert rules[0].rhs == "bar"
        assert rules[0].global_ is True
        assert skipped == []

    def test_capture_group_backref_translated(self):
        content = "regex::(\\w+)_DOM:=PREFIX_$1\n"
        rules, skipped = parse_migration_sed(content)
        assert len(rules) == 1
        # $1 is translated to Python's \1 at parse time.
        assert rules[0].rhs == "PREFIX_\\1"

    def test_double_dollar_becomes_literal_dollar(self):
        content = "regex::x:=cost is $$5\n"
        rules, _ = parse_migration_sed(content)
        assert rules[0].rhs == "cost is $5"

    def test_dollar_followed_by_non_digit_preserved(self):
        content = "regex::x:=use $env var\n"
        rules, _ = parse_migration_sed(content)
        assert rules[0].rhs == "use $env var"

    def test_missing_assign_separator_is_skipped(self):
        content = "regex::no_separator_here\n"
        rules, skipped = parse_migration_sed(content)
        assert rules == []
        assert "regex::no_separator_here" in skipped

    def test_invalid_regex_is_skipped(self):
        content = "regex::(unbalanced:=irrelevant\n"
        rules, skipped = parse_migration_sed(content)
        assert rules == []
        assert any("unbalanced" in s for s in skipped)

    def test_user_full_example_end_to_end(self):
        """The exact pattern from the issue request.

        ``CallCentre_DOM_STD_T`` → ``{{SHIPS_PROJECT}}_DOM_STD_T``
        """
        content = (
            "regex::(?i)(\\w+)_(\\w{3})_(\\w{3})_(V|T):={{SHIPS_PROJECT}}_$2_$3_$4\n"
        )
        rules, skipped = parse_migration_sed(content)
        assert skipped == []
        assert len(rules) == 1

        source = (
            "SELECT * FROM CallCentre_DOM_STD_T t "
            "JOIN CallCentre_MEM_BUS_V v ON t.id = v.id;\n"
        )
        new, hits = apply_migration_rules_to_text(source, rules)
        assert "CallCentre_" not in new
        assert "{{SHIPS_PROJECT}}_DOM_STD_T" in new
        assert "{{SHIPS_PROJECT}}_MEM_BUS_V" in new
        # Hits tracked under the original PATTERN as the key.
        assert sum(hits.values()) == 2

    def test_inline_case_insensitive_flag_works(self):
        content = "regex::(?i)foo:=BAR\n"
        rules, _ = parse_migration_sed(content)
        new, _ = apply_migration_rules_to_text("FOO foo Foo", rules)
        assert new == "BAR BAR BAR"

    def test_regex_does_not_match_means_no_substitution(self):
        content = "regex::WILLNOTMATCH:=anything\n"
        rules, _ = parse_migration_sed(content)
        new, hits = apply_migration_rules_to_text("hello world", rules)
        assert new == "hello world"
        assert hits == {}

    def test_literal_and_regex_rules_coexist(self):
        content = (
            "s/$DB_PROD/{{DB_PROD}}/g\n"
            "regex::(?i)(\\w+)_(DOM)_STD_T:={{SHIPS_PROJECT}}_$2_STD_T\n"
        )
        rules, skipped = parse_migration_sed(content)
        assert skipped == []
        assert [r.is_regex for r in rules] == [False, True]

        source = "SELECT * FROM CallCentre_DOM_STD_T WHERE x = $DB_PROD;\n"
        new, _ = apply_migration_rules_to_text(source, rules)
        assert "{{SHIPS_PROJECT}}_DOM_STD_T" in new
        assert "{{DB_PROD}}" in new

    def test_regex_rule_global_by_default(self):
        # No flag syntax in the regex:: form; should always replace every match.
        rules, _ = parse_migration_sed("regex::ab:=XY\n")
        new, _ = apply_migration_rules_to_text("ababab", rules)
        assert new == "XYXYXY"

    def test_literal_rule_with_backslash_in_rhs_not_treated_as_backref(self):
        """Regression: literal rules must NOT expand ``\\1`` as a back-ref."""
        rules, _ = parse_migration_sed("s/X/cost \\$10/g\n")
        new, _ = apply_migration_rules_to_text("price X", rules)
        # Literal RHS preserved verbatim (no expansion).
        assert new == "price cost \\$10"


# ---------------------------------------------------------------
# migrate_source_directory
# ---------------------------------------------------------------


def _make_rules(*pairs):
    """Build a list of MigrationRule from (pattern, replacement) pairs."""
    import re

    rules = []
    for raw_lhs, rhs in pairs:
        rules.append(
            MigrationRule(
                raw_lhs=raw_lhs,
                lhs=re.compile(re.escape(raw_lhs)),
                rhs=rhs,
                global_=True,
            )
        )
    return rules


class TestMigrateSourceDirectory:
    def test_replaces_placeholder_in_db_file(self, tmp_path):
        (tmp_path / "x.db").write_text(
            "CREATE DATABASE $OPR_M FROM $OPR_NODE\nAS PERM=0;\n",
            encoding="utf-8",
        )
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"), ("$OPR_NODE", "{{OPR_NODE}}"))

        result = migrate_source_directory(str(tmp_path), rules)

        assert result.files_changed == 1
        content = (tmp_path / "x.db").read_text(encoding="utf-8")
        assert "{{OPR_M}}" in content
        assert "$OPR_M" not in content

    def test_dry_run_does_not_write(self, tmp_path):
        original = "CREATE DATABASE $OPR_M FROM $OPR_NODE;\n"
        (tmp_path / "x.db").write_text(original, encoding="utf-8")
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"))

        result = migrate_source_directory(str(tmp_path), rules, dry_run=True)

        assert result.dry_run is True
        assert result.files_changed == 1
        # File must be UNCHANGED in dry-run mode.
        assert (tmp_path / "x.db").read_text(encoding="utf-8") == original

    def test_unchanged_file_not_counted(self, tmp_path):
        (tmp_path / "clean.tbl").write_text(
            "CREATE TABLE {{T_DB}}.X (Id INT);", encoding="utf-8"
        )
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"))

        result = migrate_source_directory(str(tmp_path), rules)

        assert result.files_changed == 0
        assert result.files_scanned == 1

    def test_rule_hits_counted_correctly(self, tmp_path):
        (tmp_path / "a.db").write_text("$OPR_M $OPR_M $OPR_M", encoding="utf-8")
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"))

        result = migrate_source_directory(str(tmp_path), rules)

        assert result.rule_hits.get("$OPR_M") == 3

    def test_recursive_walk(self, tmp_path):
        sub = tmp_path / "sub" / "deep"
        sub.mkdir(parents=True)
        (sub / "x.db").write_text("$OPR_M", encoding="utf-8")
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"))

        result = migrate_source_directory(str(tmp_path), rules)

        assert result.files_changed == 1

    def test_bteq_leading_command_preserved(self, tmp_path):
        """The .IF ERRORCODE BTEQ line must survive unchanged."""
        original = (
            ".IF ERRORCODE <> 0 THEN .GOTO ERR\n\n"
            "CREATE DATABASE $OPR_M FROM $OPR_NODE\nAS PERM=0;\n"
        )
        (tmp_path / "x.db").write_text(original, encoding="utf-8")
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"), ("$OPR_NODE", "{{OPR_NODE}}"))

        migrate_source_directory(str(tmp_path), rules)

        result = (tmp_path / "x.db").read_text(encoding="utf-8")
        assert ".IF ERRORCODE <> 0 THEN .GOTO ERR" in result
        assert "{{OPR_M}}" in result
        assert "{{OPR_NODE}}" in result

    def test_multiple_syntaxes_all_converted(self, tmp_path):
        """$VAR, ${VAR} and &&VAR&& in the same file all get replaced."""
        (tmp_path / "x.db").write_text("$A ${B} &&C&&", encoding="utf-8")
        rules = _make_rules(("$A", "{{A}}"), ("${B}", "{{B}}"), ("&&C&&", "{{C}}"))
        migrate_source_directory(str(tmp_path), rules)
        content = (tmp_path / "x.db").read_text(encoding="utf-8")
        assert content == "{{A}} {{B}} {{C}}"

    def test_apply_rules_to_text_does_not_touch_files(self, tmp_path):
        """Harvest can normalise legacy markers in memory."""
        source = tmp_path / "x.db"
        original = "CREATE DATABASE $OPR_M FROM $OPR_NODE;\n"
        source.write_text(original, encoding="utf-8")
        rules = _make_rules(("$OPR_M", "{{OPR_M}}"), ("$OPR_NODE", "{{OPR_NODE}}"))

        migrated, hits = apply_migration_rules_to_text(original, rules)

        assert migrated == "CREATE DATABASE {{OPR_M}} FROM {{OPR_NODE}};\n"
        assert hits == {"$OPR_M": 1, "$OPR_NODE": 1}
        assert source.read_text(encoding="utf-8") == original


# ---------------------------------------------------------------
# CLI subcommand wiring
# ---------------------------------------------------------------


class TestMigrateSourceCLI:
    def _invoke(self, argv):
        old = sys.argv
        sys.argv = ["td_release_packager"] + argv
        try:
            from td_release_packager.cli import main

            with pytest.raises(SystemExit) as ei:
                main()
            return int(ei.value.code) if ei.value.code is not None else 0
        finally:
            sys.argv = old

    def test_end_to_end_via_subcommand(self, tmp_path, capsys):
        src = tmp_path / "src"
        src.mkdir()
        (src / "x.db").write_text(
            "CREATE DATABASE $OPR_M FROM $OPR_NODE;\n", encoding="utf-8"
        )
        cfg = tmp_path / "tokenise.conf"
        cfg.write_text(
            "s/$OPR_M/{{OPR_M}}/g\ns/$OPR_NODE/{{OPR_NODE}}/g\n",
            encoding="utf-8",
        )

        rc = self._invoke(
            [
                "migrate-source",
                "--tokenise-config",
                str(cfg),
                "--source",
                str(src),
            ]
        )
        capsys.readouterr()

        assert rc == 0
        content = (src / "x.db").read_text(encoding="utf-8")
        assert "{{OPR_M}}" in content
        assert "$OPR_M" not in content

    def test_dry_run_via_subcommand(self, tmp_path, capsys):
        src = tmp_path / "src"
        src.mkdir()
        original = "CREATE DATABASE $OPR_M;\n"
        (src / "x.db").write_text(original, encoding="utf-8")
        cfg = tmp_path / "tokenise.conf"
        cfg.write_text("s/$OPR_M/{{OPR_M}}/g\n", encoding="utf-8")

        rc = self._invoke(
            [
                "migrate-source",
                "--tokenise-config",
                str(cfg),
                "--source",
                str(src),
                "--dry-run",
            ]
        )
        capsys.readouterr()

        assert rc == 0
        # File unchanged in dry-run mode.
        assert (src / "x.db").read_text(encoding="utf-8") == original

    def test_missing_config_returns_nonzero(self, tmp_path, capsys):
        rc = self._invoke(
            [
                "migrate-source",
                "--tokenise-config",
                str(tmp_path / "nope.conf"),
                "--source",
                str(tmp_path),
            ]
        )
        capsys.readouterr()
        assert rc == 1

    def test_missing_source_returns_nonzero(self, tmp_path, capsys):
        cfg = tmp_path / "tokenise.conf"
        cfg.write_text("s/$A/{{A}}/g\n", encoding="utf-8")
        rc = self._invoke(
            [
                "migrate-source",
                "--tokenise-config",
                str(cfg),
                "--source",
                str(tmp_path / "nope"),
            ]
        )
        capsys.readouterr()
        assert rc == 1


# ---------------------------------------------------------------
# Project loader: config/tokenise.conf
# ---------------------------------------------------------------


class TestProjectLoader:
    """``_load_project_legacy_migration_rules`` reads
    ``config/tokenise.conf`` from the project."""

    def _setup(self, tmp_path):
        from td_release_packager.cli import _load_project_legacy_migration_rules

        project = tmp_path / "project"
        (project / "config").mkdir(parents=True)
        return project, _load_project_legacy_migration_rules

    def test_canonical_file_loads(self, tmp_path):
        project, load = self._setup(tmp_path)
        (project / "config" / "tokenise.conf").write_text(
            "s/$A/{{A}}/g\n", encoding="utf-8"
        )
        rules = load(str(project))
        assert len(rules) == 1
        assert rules[0].raw_lhs == "$A"

    def test_missing_config_returns_empty(self, tmp_path):
        project, load = self._setup(tmp_path)
        rules = load(str(project))
        assert rules == []

    def test_legacy_filename_no_longer_recognised(self, tmp_path):
        """``config/legacy_migration.sed`` is no longer a fallback."""
        project, load = self._setup(tmp_path)
        (project / "config" / "legacy_migration.sed").write_text(
            "s/$A/{{A}}/g\n", encoding="utf-8"
        )
        rules = load(str(project))
        assert rules == []
