"""
report.py — Deployment report generator.

Produces a self-contained, Teradata-branded HTML report after
every deployment (including dry runs). The report is designed
for DBAs and release managers answering: "what happened, what
do I need to worry about, and is there anything I need to act on?"

Structure:
    1. Action Items (top) — SKIPPED/FAILED objects needing attention
    2. Deployment Summary — metadata, aggregate counts
    3. Pre-flight Results — permission/space/parse checks
    4. Object Results     — per-object table with status badges

The report is auto-generated by the deployer and saved alongside
the manifest as .deploy_report_{deployment_id}.html.
"""

import logging
import os
from datetime import datetime, timezone
from typing import Optional

from ddl_deployer.models import (
    DeployState,
    ObjectType,
    PackageDeployResult,
    PreflightResult,
)

logger = logging.getLogger(__name__)


def _display_name(obj) -> str:
    """
    Build a display name for an object.

    For two-part names (DB.Object): 'MyDB.Customer'
    For single-part names (system-scope, DCL): 'analyst_role'
    Avoids the '.analyst_role' leading-period bug.
    """
    if obj.database_name:
        return f"{obj.database_name}.{obj.object_name}"
    return obj.object_name or "(unknown)"

# -- Teradata brand colours --
_NAVY = "#00233C"
_ORANGE = "#FF5F02"
_WHITE = "#FFFFFF"
_LIGHT_BG = "#F8F9FA"
_BORDER = "#DEE2E6"

# -- Wordmark logo (extracted per standing instruction: grep '^data:image/png;base64,') --
_LOGO_B64 = (
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABVCAMAAADOrBLE"
    "AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAGb"
    "UExURf9fAgAAAP9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv///3jJeXQAAACHdFJOUwAA4/Lx9HV8gggMBOHDxL0090PNnJ6YKgGB7pTk"
    "tAfU3SD8YJ3GGf4QSfOtNgYDHk50g39kIdnqrlFBPT48I4na+u+4Uqr79vXtQNKT"
    "FGegDyfRd4jeMDkd2JBL+M4ib+nwUwJK0CbimQXoLna8ax8KK1iGyutCwS0sOkRM"
    "TRXnjBwW5ciKNyCa7VMAAAABYktHRIhrZhZaAAAACXBIWXMAAC4jAAAuIwF4pT92AA"
    "AAB3RJTUUH6gIDDSMcsQ7WtwAAAeNJREFUWMPt1tlbElEYBvCXMEhGssVwynIBCxBE"
    "MXQKynBDMAoqSElt0bKgXFpt07LM+bcdRpiGc0jOuaini/Nezjfze76zAo5Ym2py1A"
    "YLT9CkErELQAAC+E+AY80OOhLYgRYnleOtJziAejl5SgACEMC/B063naHiaucA7JDr"
    "hAuw8EQAAhCAAAQggL8MnAWXgHMk0MEJnCeBC518QBcJdPfwAa0k4PZwjQG9JKBe"
    "vMQF2Lwk4HX5OHqAv49qwR0I9v+ZQGhgMDx0ORJ06O9geESlo1wJX43Grhm57qt6"
    "wOiN+Fi5z/GJyWbtKfqn1LpJTCd/JzVTASD7bxqvJNO3oOW22jjVv3mA37xvvJms"
    "Btxp4QBG79bO1j0ZCLmYAcg5opC/r7UwqzADcwWykoO2LA+YgfkFsrJYXoiHi2wA"
    "8IiqWKFP7WNGwE5VvHpBjjxhA8JUZfpgbFJEYQAsWEqQlUJlfZefPmMBVp6TlRcwt"
    "nhHqjEgkYdfiRqHDsVYptQIQJC4AdNF06lF8eWr1ZL7EECb7rWk+blzvfbYAxuv37"
    "wNvMu/71sYS5hi/VAdaqfNtGCbH0HfG5Cl7MCnz1++bpkyv23cB9Kgs7Idv33f0T7"
    "n+xnSu/zhCcSVn7u/9vTx7wNeLG/Yd2GbHAAAAABJRU5ErkJggg=="
)

# -- Status badge styling --
_STATE_BADGES = {
    DeployState.COMPLETED: ("Completed", "#28A745", _WHITE),
    DeployState.SKIPPED: ("Skipped", "#FFC107", _NAVY),
    DeployState.FAILED: ("Failed", "#DC3545", _WHITE),
    DeployState.ROLLED_BACK: ("Rolled back", "#6C757D", _WHITE),
    DeployState.PENDING: ("Pending", "#ADB5BD", _NAVY),
    DeployState.BACKED_UP: ("Backed up", "#17A2B8", _WHITE),
    DeployState.CREATED: ("Created", "#17A2B8", _WHITE),
    DeployState.MIGRATED: ("Migrated", "#28A745", _WHITE),
}


def generate_report(
    result: PackageDeployResult,
    output_dir: str,
) -> str:
    """
    Generate a deployment report as a self-contained HTML file.

    Args:
        result:     PackageDeployResult from the deployment.
        output_dir: Directory to write the report file.

    Returns:
        Path to the generated report file.
    """
    report_filename = f".deploy_report_{result.deployment_id}.html"
    report_path = os.path.join(output_dir, report_filename)

    html = _build_html(result)

    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(html)

    logger.info("Deployment report written: %s", report_path)
    return report_path


def _build_html(result: PackageDeployResult) -> str:
    """Build the complete HTML report string."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    # Determine report mode from context
    if result.dry_run:
        mode = "DRY RUN"
    elif result.deployment_id and result.deployment_id.startswith("explain_"):
        mode = "EXPLAIN"
    else:
        mode = "DEPLOYMENT"
    status = "PASSED" if result.success else "FAILED"
    status_colour = "#28A745" if result.success else "#DC3545"

    sections = [
        _html_head(result, now, mode),
        _html_header(result, now, mode, status, status_colour),
        _html_action_items(result),
        _html_summary(result, mode),
        _html_preflight(result.preflight_result),
        _html_wave_summary(result),
        _html_object_results(result),
        _html_footer(now),
    ]

    return "\n".join(sections)


def _html_head(result, now, mode):
    """HTML document head with embedded styles."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{mode} Report — {result.deployment_id}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Inter', -apple-system, sans-serif; font-size: 14px;
         line-height: 1.6; color: {_NAVY}; background: {_WHITE}; }}
  .header {{ background: {_NAVY}; color: {_WHITE}; padding: 24px 32px;
             display: flex; align-items: center; justify-content: space-between; }}
  .header img {{ height: 28px; filter: brightness(0) invert(1); }}
  .header-right {{ text-align: right; font-size: 13px; opacity: 0.85; }}
  .header h1 {{ font-size: 20px; font-weight: 500; margin: 0; }}
  .header .status {{ display: inline-block; padding: 3px 12px; border-radius: 4px;
                     font-size: 13px; font-weight: 600; margin-left: 12px; }}
  .container {{ max-width: 960px; margin: 0 auto; padding: 24px 32px; }}
  h2 {{ font-size: 16px; font-weight: 600; color: {_NAVY}; margin: 28px 0 12px;
        padding-bottom: 6px; border-bottom: 2px solid {_ORANGE}; }}
  .action-items {{ background: #FFF3CD; border: 1px solid #FFEAA7; border-radius: 6px;
                   padding: 16px 20px; margin-bottom: 20px; }}
  .action-items.has-errors {{ background: #F8D7DA; border-color: #F5C6CB; }}
  .action-items h3 {{ font-size: 14px; font-weight: 600; margin-bottom: 8px; }}
  .action-item {{ padding: 6px 0; border-bottom: 1px solid rgba(0,0,0,0.08); }}
  .action-item:last-child {{ border-bottom: none; }}
  .no-actions {{ background: #D4EDDA; border-color: #C3E6CB; border-radius: 6px;
                 padding: 12px 20px; margin-bottom: 20px; color: #155724; }}
  .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
            gap: 12px; margin: 16px 0; }}
  .stat {{ background: {_LIGHT_BG}; border-radius: 6px; padding: 12px 16px; text-align: center; }}
  .stat .num {{ font-size: 24px; font-weight: 600; color: {_NAVY}; }}
  .stat .label {{ font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px;
                  color: #6C757D; margin-top: 2px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; margin: 12px 0; }}
  th {{ background: {_NAVY}; color: {_WHITE}; font-weight: 500; text-align: left;
        padding: 8px 12px; font-size: 12px; text-transform: uppercase;
        letter-spacing: 0.4px; }}
  td {{ padding: 8px 12px; border-bottom: 1px solid {_BORDER}; vertical-align: top; }}
  tr:hover td {{ background: #F1F3F5; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 3px;
            font-size: 11px; font-weight: 600; letter-spacing: 0.3px; }}
  .type-badge {{ background: {_LIGHT_BG}; color: {_NAVY}; font-family: 'Inter', monospace;
                 font-size: 11px; }}
  .mono {{ font-family: 'SF Mono', 'Fira Code', monospace; font-size: 12px; }}
  .warn {{ color: #856404; }}
  .err {{ color: #721C24; }}
  .check-pass {{ color: #155724; }}
  .check-fail {{ color: #721C24; font-weight: 500; }}
  .check-warn {{ color: #856404; }}
  .preflight-grid {{ display: grid; gap: 4px; }}
  .pf-row {{ display: grid; grid-template-columns: 24px 1fr; gap: 8px;
             padding: 3px 0; font-size: 13px; }}
  .footer {{ text-align: center; padding: 20px 32px; font-size: 12px;
             color: #6C757D; border-top: 1px solid {_BORDER}; margin-top: 32px; }}
  .blocker {{ background: #F8D7DA; padding: 4px 8px; border-radius: 3px;
              margin: 2px 0; font-size: 12px; }}
  .warning {{ background: #FFF3CD; padding: 4px 8px; border-radius: 3px;
              margin: 2px 0; font-size: 12px; }}
  @media print {{
    .header {{ -webkit-print-color-adjust: exact; print-color-adjust: exact; }}
    body {{ font-size: 12px; }}
  }}
</style>
</head>
<body>"""


def _html_header(result, now, mode, status, status_colour):
    """Branded header bar with logo and status."""
    return f"""
<div class="header">
  <div>
    <img src="{_LOGO_B64}" alt="Teradata">
    <h1 style="margin-top:8px">{mode} Report
      <span class="status" style="background:{status_colour}">{status}</span>
    </h1>
  </div>
  <div class="header-right">
    <div>{result.deployment_id}</div>
    <div>{now}</div>
  </div>
</div>
<div class="container">"""


def _html_action_items(result):
    """Action items section — SKIPPED and FAILED objects needing attention."""
    items = []

    for obj in result.results:
        if obj.state == DeployState.FAILED:
            items.append(
                f'<div class="action-item err">'
                f'<strong>FAILED:</strong> {_display_name(obj)} '
                f'({obj.object_type.value}) — {obj.error or "Unknown error"}'
                f'</div>'
            )
        elif obj.state == DeployState.SKIPPED:
            detail = "; ".join(obj.blockers) if obj.blockers else "Incompatible schema"
            items.append(
                f'<div class="action-item warn">'
                f'<strong>SKIPPED:</strong> {_display_name(obj)} '
                f'({obj.object_type.value}) — {detail}. '
                f'Backup preserved as {obj.backup_table}.'
                f'</div>'
            )

    if not items:
        return '<div class="no-actions">No action items — all objects deployed successfully.</div>'

    has_errors = any(o.state == DeployState.FAILED for o in result.results)
    css_class = "action-items has-errors" if has_errors else "action-items"

    return (
        f'<div class="{css_class}">'
        f'<h3>Action Items ({len(items)})</h3>'
        + "\n".join(items)
        + '</div>'
    )


def _html_summary(result, mode):
    """Deployment summary with stat cards."""
    manifest_line = (
        f'<p style="margin:8px 0; font-size:13px; color:#6C757D">'
        f'Manifest: <span class="mono">{result.manifest_path}</span></p>'
        if result.manifest_path else ""
    )

    return f"""
<h2>Summary</h2>
{manifest_line}
<div class="stats">
  <div class="stat"><div class="num">{result.total}</div><div class="label">Total</div></div>
  <div class="stat"><div class="num" style="color:#28A745">{result.completed}</div><div class="label">Completed</div></div>
  <div class="stat"><div class="num" style="color:#FFC107">{result.skipped}</div><div class="label">Skipped</div></div>
  <div class="stat"><div class="num" style="color:#DC3545">{result.failed}</div><div class="label">Failed</div></div>
  <div class="stat"><div class="num" style="color:#6C757D">{result.rolled_back}</div><div class="label">Rolled back</div></div>
</div>"""


def _html_preflight(pf: Optional[PreflightResult]):
    """Pre-flight validation results."""
    if pf is None:
        return '<h2>Pre-flight</h2><p style="color:#6C757D">Pre-flight was skipped (resume mode).</p>'

    status = "PASSED" if pf.passed else "FAILED"
    icon = "✓" if pf.passed else "✗"
    colour = "#155724" if pf.passed else "#721C24"

    # Object inventory
    inv = ", ".join(f"{v} {k}(s)" for k, v in sorted(pf.object_count.items()))

    # Show only failures and warnings to keep it concise
    check_rows = []
    for c in pf.checks:
        if not c.passed and c.severity == "ERROR":
            check_rows.append(
                f'<div class="pf-row"><span>✗</span>'
                f'<span class="check-fail">[{c.database}] {c.message}</span></div>'
            )
        elif c.severity == "WARNING":
            check_rows.append(
                f'<div class="pf-row"><span>⚠</span>'
                f'<span class="check-warn">[{c.database}] {c.message}</span></div>'
            )

    checks_html = (
        '<div class="preflight-grid">' + "\n".join(check_rows) + '</div>'
        if check_rows else
        '<p style="color:#155724; font-size:13px">All checks passed — no issues detected.</p>'
    )

    return f"""
<h2>Pre-flight <span style="color:{colour}; font-weight:500">{icon} {status}</span></h2>
<p style="font-size:13px; margin-bottom:8px">Objects: {inv}
&nbsp;|&nbsp; Databases: {", ".join(pf.databases)}
&nbsp;|&nbsp; Errors: {pf.errors} &nbsp;|&nbsp; Warnings: {pf.warnings}</p>
{checks_html}"""


def _html_wave_summary(result):
    """Wave execution summary — only shown for wave-parallel deployments."""
    if not result.is_wave_parallel:
        return ""

    rows = []
    for ws in result.wave_summaries:
        # Colour the row based on outcome
        if ws.failed > 0:
            row_style = 'background:#F8D7DA'
        elif ws.skipped > 0 and ws.completed == 0:
            row_style = 'background:#FFF3CD'
        else:
            row_style = ''

        style_attr = f' style="{row_style}"' if row_style else ''

        rows.append(
            f'<tr{style_attr}>'
            f'<td style="text-align:center;font-weight:500">{ws.wave_number}</td>'
            f'<td style="text-align:center">{ws.total}</td>'
            f'<td style="text-align:center;color:#28A745">{ws.completed}</td>'
            f'<td style="text-align:center;color:#DC3545">{ws.failed}</td>'
            f'<td style="text-align:center;color:#6C757D">{ws.skipped}</td>'
            f'<td style="text-align:right" class="mono">{ws.duration_ms:,} ms</td>'
            f'</tr>'
        )

    total_duration = sum(ws.duration_ms for ws in result.wave_summaries)

    return f"""
<h2>Wave Execution ({result.num_streams} stream{"s" if result.num_streams != 1 else ""})</h2>
<table>
<thead><tr>
  <th style="width:60px">Wave</th>
  <th style="width:70px">Objects</th>
  <th style="width:80px">Completed</th>
  <th style="width:70px">Failed</th>
  <th style="width:70px">Skipped</th>
  <th style="width:100px;text-align:right">Duration</th>
</tr></thead>
<tbody>
{"".join(rows)}
<tr style="border-top:2px solid {_NAVY}">
  <td style="font-weight:500" colspan="5">Total</td>
  <td style="text-align:right;font-weight:500" class="mono">{total_duration:,} ms</td>
</tr>
</tbody>
</table>"""


def _html_object_results(result):
    """Per-object results table with optional wave column."""
    has_waves = result.is_wave_parallel
    rows = []

    for i, obj in enumerate(result.results, 1):
        badge_label, badge_bg, badge_fg = _STATE_BADGES.get(
            obj.state, ("Unknown", "#ADB5BD", _NAVY)
        )

        type_html = f'<span class="badge type-badge">{obj.object_type.value}</span>'
        status_html = (
            f'<span class="badge" style="background:{badge_bg};color:{badge_fg}">'
            f'{badge_label}</span>'
        )

        details = [obj.message]
        if obj.backup_table:
            details.append(f'Backup: <span class="mono">{obj.backup_table}</span>')
        if obj.rows_migrated > 0:
            details.append(f'Rows migrated: {obj.rows_migrated:,}')

        # Deploy intent badge
        intent_html = ""
        if obj.deploy_intent:
            intent_label = obj.deploy_intent.value if hasattr(obj.deploy_intent, 'value') else str(obj.deploy_intent)
            intent_html = f'<span class="badge" style="background:#E9ECEF;color:{_NAVY}">{intent_label}</span> '

        # Rollback indicator
        rollback_html = ""
        if obj.rollback_file:
            rb_name = os.path.basename(obj.rollback_file) if '/' in str(obj.rollback_file) else obj.rollback_file
            rollback_html = f'<div style="color:#28A745;font-size:12px">↩ Rollback available: <span class="mono">{rb_name}</span></div>'
        elif obj.prior_existed and obj.state == DeployState.COMPLETED:
            rollback_html = '<div style="color:#6C757D;font-size:12px">↩ No rollback (table uses backup strategy)</div>'

        extra_html = ""
        for b in obj.blockers:
            extra_html += f'<div class="blocker">✗ {b}</div>'
        for w in obj.warnings:
            extra_html += f'<div class="warning">⚠ {w}</div>'

        wave_cell = ""
        if has_waves:
            wn = obj.wave_number if obj.wave_number else "—"
            wave_cell = f'<td style="text-align:center">{wn}</td>'

        # Source file name
        file_html = ""
        if hasattr(obj, 'ddl_file') and obj.ddl_file:
            file_html = f'<span class="mono" style="font-size:11px;color:#6C757D">{obj.ddl_file}</span>'

        rows.append(
            f'<tr>'
            f'<td style="text-align:center;color:#6C757D">{i}</td>'
            f'{wave_cell}'
            f'<td class="mono">{_display_name(obj)}</td>'
            f'<td>{intent_html}{type_html}</td>'
            f'<td>{status_html}</td>'
            f'<td>{"<br>".join(details)}'
            f'{("<br>" + file_html) if file_html else ""}'
            f'{rollback_html}{extra_html}</td>'
            f'</tr>'
        )

    if not rows:
        return '<h2>Object Results</h2><p style="color:#6C757D">No objects were processed.</p>'

    wave_header = '<th style="width:50px">Wave</th>' if has_waves else ''

    return f"""
<h2>Object Results</h2>
<table>
<thead><tr>
  <th style="width:40px">#</th>
  {wave_header}
  <th>Object</th>
  <th style="width:100px">Type</th>
  <th style="width:100px">Status</th>
  <th>Details</th>
</tr></thead>
<tbody>
{"".join(rows)}
</tbody>
</table>"""


def _html_footer(now):
    """Report footer."""
    return f"""
</div>
<div class="footer">
  Generated by ddl_deployer v2.0 &nbsp;|&nbsp; {now}
</div>
</body>
</html>"""
