"""
report.py — Deployment report generator.

Produces a self-contained, Teradata-branded HTML report after
every deployment (including dry runs). The report is designed
for DBAs and release managers answering: "what happened, what
do I need to worry about, and is there anything I need to act on?"

Structure:
    1. Action Items (top) — SKIPPED/FAILED objects needing attention
    2. Deployment Summary — metadata, aggregate counts
    3. Pre-flight Results — permission/space/parse checks
    4. Object Results     — per-object table with status badges

The report is auto-generated by the deployer and saved alongside
the manifest as .deploy_report_{deployment_id}.html.
"""

import logging
import os
from datetime import datetime, timezone
from typing import Optional, Tuple

from ddl_deployer.models import (
    DeployState,
    PackageDeployResult,
    PreflightResult,
)
from ddl_deployer.provenance import ProvenanceChain, ProvenanceDocument
from ddl_deployer.provenance_renderer import PROVENANCE_CSS, render_chain

logger = logging.getLogger(__name__)


def _display_name(obj) -> str:
    """
    Build a display name for an object.

    For two-part names (DB.Object): 'MyDB.Customer'
    For single-part names (system-scope, DCL): 'analyst_role'
    Avoids the '.analyst_role' leading-period bug.
    """
    if obj.database_name:
        return f"{obj.database_name}.{obj.object_name}"
    return obj.object_name or "(unknown)"


# -- Teradata brand colours --
_NAVY = "#00233C"
_ORANGE = "#FF5F02"
_WHITE = "#FFFFFF"
_LIGHT_BG = "#F8F9FA"
_BORDER = "#DEE2E6"

# -- Wordmark logo (extracted per standing instruction: grep '^data:image/png;base64,') --
_LOGO_B64 = (
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABVCAMAAADOrBLE"
    "AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAGb"
    "UExURf9fAgAAAP9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9fAv9f"
    "Av9fAv///3jJeXQAAACHdFJOUwAA4/Lx9HV8gggMBOHDxL0090PNnJ6YKgGB7pTk"
    "tAfU3SD8YJ3GGf4QSfOtNgYDHk50g39kIdnqrlFBPT48I4na+u+4Uqr79vXtQNKT"
    "FGegDyfRd4jeMDkd2JBL+M4ib+nwUwJK0CbimQXoLna8ax8KK1iGyutCwS0sOkRM"
    "TRXnjBwW5ciKNyCa7VMAAAABYktHRIhrZhZaAAAACXBIWXMAAC4jAAAuIwF4pT92AA"
    "AAB3RJTUUH6gIDDSMcsQ7WtwAAAeNJREFUWMPt1tlbElEYBvCXMEhGssVwynIBCxBE"
    "MXQKynBDMAoqSElt0bKgXFpt07LM+bcdRpiGc0jOuaini/Nezjfze76zAo5Ym2py1A"
    "YLT9CkErELQAAC+E+AY80OOhLYgRYnleOtJziAejl5SgACEMC/B063naHiaucA7JDr"
    "hAuw8EQAAhCAAAQggL8MnAWXgHMk0MEJnCeBC518QBcJdPfwAa0k4PZwjQG9JKBe"
    "vMQF2Lwk4HX5OHqAv49qwR0I9v+ZQGhgMDx0ORJ06O9geESlo1wJX43Grhm57qt6"
    "wOiN+Fi5z/GJyWbtKfqn1LpJTCd/JzVTASD7bxqvJNO3oOW22jjVv3mA37xvvJms"
    "Btxp4QBG79bO1j0ZCLmYAcg5opC/r7UwqzADcwWykoO2LA+YgfkFsrJYXoiHi2wA"
    "8IiqWKFP7WNGwE5VvHpBjjxhA8JUZfpgbFJEYQAsWEqQlUJlfZefPmMBVp6TlRcwt"
    "nhHqjEgkYdfiRqHDsVYptQIQJC4AdNF06lF8eWr1ZL7EECb7rWk+blzvfbYAxuv37"
    "wNvMu/71sYS5hi/VAdaqfNtGCbH0HfG5Cl7MCnz1++bpkyv23cB9Kgs7Idv33f0T7"
    "n+xnSu/zhCcSVn7u/9vTx7wNeLG/Yd2GbHAAAAABJRU5ErkJggg=="
)

# -- Status badge styling --
_STATE_BADGES = {
    DeployState.COMPLETED: ("Completed", "#28A745", _WHITE),
    DeployState.SKIPPED: ("Skipped", "#FFC107", _NAVY),
    DeployState.FAILED: ("Failed", "#DC3545", _WHITE),
    DeployState.ROLLED_BACK: ("Rolled back", "#6C757D", _WHITE),
    DeployState.PENDING: ("Pending", "#ADB5BD", _NAVY),
    DeployState.BACKED_UP: ("Backed up", "#17A2B8", _WHITE),
    DeployState.CREATED: ("Created", "#17A2B8", _WHITE),
    DeployState.MIGRATED: ("Migrated", "#28A745", _WHITE),
}


def generate_report(
    result: PackageDeployResult,
    output_dir: str,
) -> str:
    """
    Generate a deployment report as a self-contained HTML file.

    Args:
        result:     PackageDeployResult from the deployment.
        output_dir: Directory to write the report file.

    Returns:
        Path to the generated report file.
    """
    report_filename = f".deploy_report_{result.deployment_id}.html"
    report_path = os.path.join(output_dir, report_filename)

    # Load provenance map if available (built by the builder).
    # Maps resolved package paths → original project source paths.
    provenance, prov_status = _load_provenance(output_dir)

    html = _build_html(result, provenance, prov_status)

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(html)

    logger.info("Deployment report written: %s", report_path)
    return report_path


def _load_provenance(pkg_dir: str) -> Tuple[Optional[ProvenanceDocument], str]:
    """
    Load the v2 ProvenanceDocument from _provenance.json if it exists.

    The provenance document records the full filename-transformation
    chain (source → eponymous → token-resolved → package) for every
    payload file. The report uses this to render a drill-down on
    failed/skipped objects so the DBA can see exactly where in the
    build pipeline each path was rewritten.

    The deployer commonly writes its outputs (manifest, report) into
    a ``logs/`` subdirectory whilst ``_provenance.json`` lives at the
    package root, so this function walks UP from ``pkg_dir`` looking
    for the file. Stops at filesystem root or after 5 levels — a
    reasonable bound that avoids unbounded scans on deep mounts.
    The first match wins, so when there's a provenance file at both
    the package root and an ancestor, the closer (more specific) one
    is used.

    Args:
        pkg_dir: Directory the deployer is using for its outputs.
                 May be the package root, or a ``logs/`` subdirectory.

    Returns:
        ``(document, status_message)`` where:
            document:        ProvenanceDocument if the file loaded
                             successfully, else None.
            status_message:  Empty string on success. Otherwise a
                             human-readable explanation suitable for
                             rendering in the report header so the DBA
                             knows why drill-downs are absent.
    """
    candidate = os.path.abspath(pkg_dir)
    for _ in range(6):  # current dir + up to 5 ancestors
        provenance_path = os.path.join(candidate, "_provenance.json")
        if os.path.exists(provenance_path):
            try:
                return ProvenanceDocument.load(provenance_path), ""
            except ValueError as e:
                # Version mismatch or schema error — log and degrade
                # gracefully. Report will render without drill-down.
                msg = str(e)
                logger.warning(
                    "Could not load %s (drill-down disabled): %s",
                    provenance_path,
                    msg,
                )
                return None, (
                    f"_provenance.json at {provenance_path} could not "
                    f"be loaded — drill-downs disabled. Reason: {msg}"
                )
            except Exception as e:
                msg = str(e)
                logger.warning("Could not parse %s: %s", provenance_path, msg)
                return None, (
                    f"_provenance.json at {provenance_path} could not "
                    f"be parsed — drill-downs disabled. Reason: {msg}"
                )

        parent = os.path.dirname(candidate)
        if parent == candidate:
            break  # reached filesystem root
        candidate = parent

    # Not found in pkg_dir or any of its ancestors
    return None, (
        "_provenance.json not present in this package directory tree. "
        "Drill-downs and source-edit hints are disabled. To enable: "
        "rebuild the package with the current version of the builder, "
        "and verify the report is being written within the package "
        "directory tree."
    )


def _build_html(
    result: PackageDeployResult,
    provenance: Optional[ProvenanceDocument] = None,
    provenance_status: str = "",
) -> str:
    """Build the complete HTML report string."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    # Determine report mode from context.
    # REPLAY takes precedence over DEPLOYMENT when nothing was
    # processed but prior COMPLETED objects were verified — this is
    # an honest signal to the DBA that this run did no work.
    if result.dry_run:
        mode = "DRY RUN"
    elif result.deployment_id and result.deployment_id.startswith("explain_"):
        mode = "EXPLAIN"
    elif result.is_noop_redeploy:
        mode = "REPLAY"
    else:
        mode = "DEPLOYMENT"
    status = "PASSED" if result.success else "FAILED"
    status_colour = "#28A745" if result.success else "#DC3545"

    sections = [
        _html_head(result, now, mode),
        _html_header(result, now, mode, status, status_colour),
        _html_provenance_notice(provenance_status),
        _html_action_items(result, provenance),
        _html_summary(result, mode),
        _html_preflight(result.preflight_result),
        _html_wave_summary(result),
        _html_object_results(result, provenance),
        _html_footer(now),
    ]

    return "\n".join(sections)


def _html_provenance_notice(status_message: str) -> str:
    """
    Render a small, dismissible-looking banner explaining why
    drill-downs are disabled. Returns empty string when provenance
    loaded successfully (status_message == "").

    Sits just below the main header so the DBA sees it before
    scrolling into the results table — without being so loud that
    it hides successful deployments.
    """
    if not status_message:
        return ""

    return (
        '<div style="background:#FFF8E1;border:1px solid #FFE082;'
        "border-left:4px solid #FFC107;padding:10px 14px;margin:0 0 16px 0;"
        'border-radius:4px;font-size:13px;color:#5D4E00">'
        "<strong>ℹ Provenance unavailable</strong> &nbsp;"
        f"{status_message}"
        "</div>"
    )


def _html_head(result, now, mode):
    """HTML document head with embedded styles."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{mode} Report — {result.deployment_id}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Inter', -apple-system, sans-serif; font-size: 14px;
         line-height: 1.6; color: {_NAVY}; background: {_WHITE}; }}
  .header {{ background: {_NAVY}; color: {_WHITE}; padding: 24px 32px;
             display: flex; align-items: center; justify-content: space-between; }}
  .header img {{ height: 28px; filter: brightness(0) invert(1); }}
  .header-right {{ text-align: right; font-size: 13px; opacity: 0.85; }}
  .header h1 {{ font-size: 20px; font-weight: 500; margin: 0; }}
  .header .status {{ display: inline-block; padding: 3px 12px; border-radius: 4px;
                     font-size: 13px; font-weight: 600; margin-left: 12px; }}
  .container {{ max-width: 960px; margin: 0 auto; padding: 24px 32px; }}
  h2 {{ font-size: 16px; font-weight: 600; color: {_NAVY}; margin: 28px 0 12px;
        padding-bottom: 6px; border-bottom: 2px solid {_ORANGE}; }}
  .action-items {{ background: #FFF3CD; border: 1px solid #FFEAA7; border-radius: 6px;
                   padding: 16px 20px; margin-bottom: 20px; }}
  .action-items.has-errors {{ background: #F8D7DA; border-color: #F5C6CB; }}
  .action-items h3 {{ font-size: 14px; font-weight: 600; margin-bottom: 8px; }}
  .action-item {{ padding: 6px 0; border-bottom: 1px solid rgba(0,0,0,0.08);
                   overflow-wrap: break-word; word-break: break-word; }}
  .action-item:last-child {{ border-bottom: none; }}
  .action-item .path-short {{ color: #6C757D; font-size: 12px; }}
  .action-item .path-full {{ display: none; }}
  /* Collapsible action-item groups */
  .action-group {{ margin: 0 -20px; padding: 0 20px; }}
  .action-group + .action-group {{ border-top: 1px solid rgba(0,0,0,0.08); margin-top: 6px; padding-top: 6px; }}
  .action-group > summary {{
    cursor: pointer; font-size: 13px; font-weight: 600;
    padding: 6px 0; list-style: none; user-select: none;
  }}
  .action-group > summary::-webkit-details-marker {{ display: none; }}
  .action-group > summary::before {{
    content: "\25B8"; display: inline-block;
    margin-right: 6px; transition: transform 0.15s ease; color: {_ORANGE};
  }}
  .action-group[open] > summary::before {{ transform: rotate(90deg); }}
  .action-group > summary:hover {{ opacity: 0.8; }}
  .no-actions {{ background: #D4EDDA; border-color: #C3E6CB; border-radius: 6px;
                 padding: 12px 20px; margin-bottom: 20px; color: #155724; }}
  .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
            gap: 12px; margin: 16px 0; }}
  .stat {{ background: {_LIGHT_BG}; border-radius: 6px; padding: 12px 16px; text-align: center; }}
  .stat .num {{ font-size: 24px; font-weight: 600; color: {_NAVY}; }}
  .stat .label {{ font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px;
                  color: #6C757D; margin-top: 2px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; margin: 12px 0; }}
  th {{ background: {_NAVY}; color: {_WHITE}; font-weight: 500; text-align: left;
        padding: 8px 12px; font-size: 12px; text-transform: uppercase;
        letter-spacing: 0.4px; }}
  td {{ padding: 8px 12px; border-bottom: 1px solid {_BORDER}; vertical-align: top; }}
  tr:hover td {{ background: #F1F3F5; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 3px;
            font-size: 11px; font-weight: 600; letter-spacing: 0.3px; }}
  .type-badge {{ background: {_LIGHT_BG}; color: {_NAVY}; font-family: 'Inter', monospace;
                 font-size: 11px; }}
  .mono {{ font-family: 'SF Mono', 'Fira Code', monospace; font-size: 12px; }}
  .warn {{ color: #856404; }}
  .err {{ color: #721C24; }}
  .check-pass {{ color: #155724; }}
  .check-fail {{ color: #721C24; font-weight: 500; }}
  .check-warn {{ color: #856404; }}
  .preflight-grid {{ display: grid; gap: 4px; }}
  .pf-row {{ display: grid; grid-template-columns: 24px 1fr; gap: 8px;
             padding: 3px 0; font-size: 13px; }}
  .footer {{ text-align: center; padding: 20px 32px; font-size: 12px;
             color: #6C757D; border-top: 1px solid {_BORDER}; margin-top: 32px; }}
  .blocker {{ background: #F8D7DA; padding: 4px 8px; border-radius: 3px;
              margin: 2px 0; font-size: 12px; }}
  .warning {{ background: #FFF3CD; padding: 4px 8px; border-radius: 3px;
              margin: 2px 0; font-size: 12px; }}
  @media print {{
    .header {{ -webkit-print-color-adjust: exact; print-color-adjust: exact; }}
    body {{ font-size: 12px; }}
  }}
  {PROVENANCE_CSS}
</style>
</head>
<body>"""


def _html_header(result, now, mode, status, status_colour):
    """Branded header bar with logo and status."""
    return f"""
<div class="header">
  <div>
    <img src="{_LOGO_B64}" alt="Teradata">
    <h1 style="margin-top:8px">{mode} Report
      <span class="status" style="background:{status_colour}">{status}</span>
    </h1>
  </div>
  <div class="header-right">
    <div>{result.deployment_id}</div>
    <div>{now}</div>
  </div>
</div>
<div class="container">"""


def _filename_only(path: str) -> str:
    """
    Extract the filename portion of a path regardless of separator
    style. Necessary because ``os.path.basename`` is OS-dependent —
    on POSIX it does not treat ``\\`` as a separator, so a Windows-
    style path like ``views\\X.viw`` returned from a Windows deployer
    won't be split correctly when the renderer runs on Linux (and
    vice versa, though that's the rarer direction).

    The provenance document is built on the build host with forward
    slashes; the deployer's ``ddl_file`` uses whatever separator the
    OS produced. Normalising both before comparison makes the lookup
    portable across hosts.
    """
    if not path:
        return ""
    # Normalise both separator styles, then take last component.
    return path.replace("\\", "/").rsplit("/", 1)[-1]


def _lookup_chain(
    ddl_file: Optional[str],
    provenance: Optional[ProvenanceDocument],
) -> Optional[ProvenanceChain]:
    """
    Look up the ProvenanceChain for a given object's ddl_file.

    Matches by filename basename since ddl_file uses a shortened
    path while ProvenanceDocument keys use the full
    package-relative path. Path-separator agnostic — handles
    both ``views\\X.viw`` (Windows) and ``views/X.viw`` (POSIX)
    against provenance keys regardless of host OS.

    Args:
        ddl_file:    The ddl_file value from ObjectDeployResult.
        provenance:  Loaded ProvenanceDocument, or None.

    Returns:
        The matching chain, or None if no match.
    """
    if not ddl_file or provenance is None:
        return None
    target = _filename_only(ddl_file)
    for pkg_path, chain in provenance.entries.items():
        if _filename_only(pkg_path) == target:
            return chain
    return None


def _lookup_provenance(
    ddl_file: Optional[str],
    provenance: Optional[ProvenanceDocument],
) -> str:
    """
    Look up the original source path for a given object's ddl_file.

    Convenience wrapper around _lookup_chain that returns just the
    source-stage path. Used by the existing "✎ Edit source" lines
    in Action Items and Object Results.

    Args:
        ddl_file:    The ddl_file value from ObjectDeployResult.
        provenance:  Loaded ProvenanceDocument, or None.

    Returns:
        Original source path, or empty string if not found.
    """
    chain = _lookup_chain(ddl_file, provenance)
    if chain is None:
        return ""
    return chain.source_path()


def _shorten_path(text: str) -> str:
    """Replace full absolute paths in a string with just the filename.

    Keeps the full path in a ``title`` attribute so it's accessible
    on hover, but stops the action items panel from being overwhelmed
    by long Windows/Linux paths.

    Detects path-like substrings: tokens that contain a path separator
    and end with a file extension.
    """
    import re as _re

    # Match an absolute path (Windows or Unix) referencing a file.
    # Captures everything from a drive letter or leading slash through
    # an extension-bearing filename.
    _PATH_RE = _re.compile(
        r'(?:[A-Za-z]:\\|/)(?:[^\s<>"\']+[/\\])+([^\s<>"\']+\.[A-Za-z0-9]{1,6})'
    )

    def _replace(m):
        full = m.group(0)
        basename = m.group(1)
        return (
            f'<span class="path-short" title="{full}">{basename}</span>'
        )

    return _PATH_RE.sub(_replace, text)


def _html_action_items(result, provenance: Optional[ProvenanceDocument] = None):
    """Action items section — SKIPPED and FAILED objects, grouped and collapsible.

    FAILED items are shown expanded by default (they need attention).
    SKIPPED items are collapsed by default — the DBA can open the group
    to inspect them, but they don't drown the report when there are
    hundreds of expected skips (prereq-exempt, not-applicable, etc.).
    """
    failed_items = []
    skipped_items = []

    for obj in result.results:
        if obj.state == DeployState.FAILED:
            source = ""
            if hasattr(obj, "ddl_file") and obj.ddl_file:
                source = (
                    f' <span class="mono" style="font-size:12px">'
                    f"[{obj.ddl_file}]</span>"
                )
            origin = _lookup_provenance(getattr(obj, "ddl_file", None), provenance)
            provenance_html = ""
            if origin:
                provenance_html = (
                    f'<div style="font-size:11px;color:#6C757D;margin-top:4px">'
                    f'✎ Edit source: <span class="mono">{origin}</span>'
                    f"</div>"
                )
            failed_items.append(
                f'<div class="action-item err">'
                f"<strong>FAILED:</strong> {_display_name(obj)} "
                f"({obj.object_type.value}) — "
                f"{_shorten_path(obj.error or 'Unknown error')}{source}"
                f"{provenance_html}"
                f"</div>"
            )

        elif obj.state == DeployState.SKIPPED:
            if obj.blockers:
                detail = "; ".join(obj.blockers)
            elif obj.message:
                detail = obj.message
            else:
                detail = "Skipped (no further detail)"
            backup_note = ""
            if obj.backup_table:
                backup_note = f" Backup preserved as {obj.backup_table}."
            source = ""
            if hasattr(obj, "ddl_file") and obj.ddl_file:
                source = (
                    f' <span class="mono" style="font-size:12px">'
                    f"[{obj.ddl_file}]</span>"
                )
            skipped_items.append(
                f'<div class="action-item warn">'
                f"<strong>SKIPPED:</strong> {_display_name(obj)} "
                f"({obj.object_type.value}) — "
                f"{_shorten_path(detail)}.{backup_note}{source}"
                f"</div>"
            )

    total = len(failed_items) + len(skipped_items)

    if total == 0:
        if getattr(result, "is_noop_redeploy", False):
            prior_count = len(getattr(result, "prior_completed", []))
            return (
                '<div class="no-actions">'
                f"No action items — all {prior_count} object"
                f"{'s' if prior_count != 1 else ''} were already deployed "
                "in a previous run and verified as still present in the "
                "database. Nothing was processed this run."
                "</div>"
            )
        return '<div class="no-actions">No action items — all objects deployed successfully.</div>'

    has_errors = bool(failed_items)
    css_class = "action-items has-errors" if has_errors else "action-items"

    parts = [f'<div class="{css_class}"><h3>Action Items ({total})</h3>']

    # -- FAILED group: open by default so the DBA sees them immediately --
    if failed_items:
        n = len(failed_items)
        parts.append(
            f'<details class="action-group" open>'
            f'<summary class="err">✗ {n} Failed — requires attention</summary>'
            + "\n".join(failed_items)
            + "</details>"
        )

    # -- SKIPPED group: collapsed by default --
    # May contain hundreds of PREREQ_EXEMPT, not-applicable, etc.
    # The DBA can expand to inspect but doesn't have to wade through them.
    if skipped_items:
        n = len(skipped_items)
        # Build a compact sub-summary showing counts by skip reason.
        # Groups: PREREQ_EXEMPT, NOT_APPLICABLE, ALREADY_DEPLOYED, other.
        prereq_count = sum(
            1 for o in result.results
            if o.state == DeployState.SKIPPED
            and "PREREQ_EXEMPT" in (o.message or "")
        )
        not_app_count = sum(
            1 for o in result.results
            if o.state == DeployState.SKIPPED
            and "not applicable" in (o.message or "").lower()
            and "PREREQ_EXEMPT" not in (o.message or "")
        )
        other_count = n - prereq_count - not_app_count

        sub_parts = []
        if prereq_count:
            sub_parts.append(f"{prereq_count} prereq-exempt")
        if not_app_count:
            sub_parts.append(f"{not_app_count} not applicable")
        if other_count:
            sub_parts.append(f"{other_count} other")
        sub = f" ({', '.join(sub_parts)})" if sub_parts else ""

        parts.append(
            f'<details class="action-group">'
            f"<summary>○ {n} Skipped{sub} — click to expand</summary>"
            + "\n".join(skipped_items)
            + "</details>"
        )

    parts.append("</div>")
    return "\n".join(parts)


def _html_summary(result, mode):
    """Deployment summary with stat cards."""
    manifest_line = (
        f'<p style="margin:8px 0; font-size:13px; color:#6C757D">'
        f'Manifest: <span class="mono">{result.manifest_path}</span></p>'
        if result.manifest_path
        else ""
    )

    # In REPLAY mode the standard manifest-summary counts are
    # misleading — `result.completed` reflects every COMPLETED row
    # in the manifest, including objects deployed in earlier runs.
    # Show this run's actual work (zero) and call out the prior
    # count as a separate "Verified" card.
    if mode == "REPLAY":
        prior_count = len(getattr(result, "prior_completed", []))
        return f"""
<h2>Summary</h2>
{manifest_line}
<p style="margin:0 0 12px 0; font-size:13px; color:#6C757D">
  This run did not deploy any objects. The figures below show prior-run
  state verified against the database.
</p>
<div class="stats">
  <div class="stat"><div class="num">{result.total}</div><div class="label">Total</div></div>
  <div class="stat"><div class="num" style="color:#17A2B8">{prior_count}</div><div class="label">Verified (prior)</div></div>
  <div class="stat"><div class="num" style="color:#28A745">0</div><div class="label">Deployed (this run)</div></div>
  <div class="stat"><div class="num" style="color:#FFC107">{result.skipped}</div><div class="label">Skipped</div></div>
  <div class="stat"><div class="num" style="color:#DC3545">{result.failed}</div><div class="label">Failed</div></div>
</div>"""

    return f"""
<h2>Summary</h2>
{manifest_line}
<div class="stats">
  <div class="stat"><div class="num">{result.total}</div><div class="label">Total</div></div>
  <div class="stat"><div class="num" style="color:#28A745">{result.completed}</div><div class="label">Completed</div></div>
  <div class="stat"><div class="num" style="color:#FFC107">{result.skipped}</div><div class="label">Skipped</div></div>
  <div class="stat"><div class="num" style="color:#DC3545">{result.failed}</div><div class="label">Failed</div></div>
  <div class="stat"><div class="num" style="color:#6C757D">{result.rolled_back}</div><div class="label">Rolled back</div></div>
</div>"""


def _html_preflight(pf: Optional[PreflightResult]):
    """Pre-flight validation results."""
    if pf is None:
        return '<h2>Pre-flight</h2><p style="color:#6C757D">Pre-flight was skipped (resume mode).</p>'

    status = "PASSED" if pf.passed else "FAILED"
    icon = "✓" if pf.passed else "✗"
    colour = "#155724" if pf.passed else "#721C24"

    # Object inventory
    inv = ", ".join(f"{v} {k}(s)" for k, v in sorted(pf.object_count.items()))

    # Show only failures and warnings to keep it concise
    check_rows = []
    for c in pf.checks:
        if not c.passed and c.severity == "ERROR":
            check_rows.append(
                f'<div class="pf-row"><span>✗</span>'
                f'<span class="check-fail">[{c.database}] {c.message}</span></div>'
            )
        elif c.severity == "WARNING":
            check_rows.append(
                f'<div class="pf-row"><span>⚠</span>'
                f'<span class="check-warn">[{c.database}] {c.message}</span></div>'
            )

    checks_html = (
        '<div class="preflight-grid">' + "\n".join(check_rows) + "</div>"
        if check_rows
        else '<p style="color:#155724; font-size:13px">All checks passed — no issues detected.</p>'
    )

    return f"""
<h2>Pre-flight <span style="color:{colour}; font-weight:500">{icon} {status}</span></h2>
<p style="font-size:13px; margin-bottom:8px">Objects: {inv}
&nbsp;|&nbsp; Databases: {", ".join(pf.databases)}
&nbsp;|&nbsp; Errors: {pf.errors} &nbsp;|&nbsp; Warnings: {pf.warnings}</p>
{checks_html}"""


def _html_wave_summary(result):
    """Wave execution summary — only shown for wave-parallel deployments."""
    if not result.is_wave_parallel:
        return ""

    rows = []
    for ws in result.wave_summaries:
        # Colour the row based on outcome
        if ws.failed > 0:
            row_style = "background:#F8D7DA"
        elif ws.skipped > 0 and ws.completed == 0:
            row_style = "background:#FFF3CD"
        else:
            row_style = ""

        style_attr = f' style="{row_style}"' if row_style else ""

        rows.append(
            f"<tr{style_attr}>"
            f'<td style="text-align:center;font-weight:500">{ws.wave_number}</td>'
            f'<td style="text-align:center">{ws.total}</td>'
            f'<td style="text-align:center;color:#28A745">{ws.completed}</td>'
            f'<td style="text-align:center;color:#DC3545">{ws.failed}</td>'
            f'<td style="text-align:center;color:#6C757D">{ws.skipped}</td>'
            f'<td style="text-align:right" class="mono">{ws.duration_ms:,} ms</td>'
            f"</tr>"
        )

    total_duration = sum(ws.duration_ms for ws in result.wave_summaries)

    return f"""
<h2>Wave Execution ({result.num_streams} stream{"s" if result.num_streams != 1 else ""})</h2>
<table>
<thead><tr>
  <th style="width:60px">Wave</th>
  <th style="width:70px">Objects</th>
  <th style="width:80px">Completed</th>
  <th style="width:70px">Failed</th>
  <th style="width:70px">Skipped</th>
  <th style="width:100px;text-align:right">Duration</th>
</tr></thead>
<tbody>
{"".join(rows)}
<tr style="border-top:2px solid {_NAVY}">
  <td style="font-weight:500" colspan="5">Total</td>
  <td style="text-align:right;font-weight:500" class="mono">{total_duration:,} ms</td>
</tr>
</tbody>
</table>"""


def _html_object_results(result, provenance: Optional[ProvenanceDocument] = None):
    """Per-object results table with optional wave column."""
    has_waves = result.is_wave_parallel
    rows = []

    # Column count determines the colspan for the drill-down row that
    # spans the table beneath each failed/skipped object's main row.
    # Without waves: 6 columns (#, Object, Type, Status, Source, Details)
    # With waves:    7 columns (adds Wave between # and Object)
    drilldown_colspan = 7 if has_waves else 6

    for i, obj in enumerate(result.results, 1):
        badge_label, badge_bg, badge_fg = _STATE_BADGES.get(
            obj.state, ("Unknown", "#ADB5BD", _NAVY)
        )

        type_html = f'<span class="badge type-badge">{obj.object_type.value}</span>'
        status_html = (
            f'<span class="badge" style="background:{badge_bg};color:{badge_fg}">'
            f"{badge_label}</span>"
        )

        details = [obj.message]
        if obj.backup_table:
            details.append(f'Backup: <span class="mono">{obj.backup_table}</span>')
        if obj.rows_migrated > 0:
            details.append(f"Rows migrated: {obj.rows_migrated:,}")

        # Deploy intent badge
        intent_html = ""
        if obj.deploy_intent:
            intent_label = (
                obj.deploy_intent.value
                if hasattr(obj.deploy_intent, "value")
                else str(obj.deploy_intent)
            )
            intent_html = f'<span class="badge" style="background:#E9ECEF;color:{_NAVY}">{intent_label}</span> '

        # Rollback indicator
        rollback_html = ""
        if obj.rollback_file:
            rb_name = (
                os.path.basename(obj.rollback_file)
                if "/" in str(obj.rollback_file)
                else obj.rollback_file
            )
            rollback_html = f'<div style="color:#28A745;font-size:12px">↩ Rollback available: <span class="mono">{rb_name}</span></div>'
        elif obj.prior_existed and obj.state == DeployState.COMPLETED:
            rollback_html = '<div style="color:#6C757D;font-size:12px">↩ No rollback (table uses backup strategy)</div>'

        extra_html = ""
        for b in obj.blockers:
            extra_html += f'<div class="blocker">✗ {b}</div>'
        for w in obj.warnings:
            extra_html += f'<div class="warning">⚠ {w}</div>'

        wave_cell = ""
        if has_waves:
            wn = obj.wave_number if obj.wave_number else "—"
            wave_cell = f'<td style="text-align:center">{wn}</td>'

        # Source file — dedicated column
        source_file = ""
        if hasattr(obj, "ddl_file") and obj.ddl_file:
            source_file = obj.ddl_file

        # Provenance — show original source path for failed/skipped
        # items so the DBA knows which project file to edit.
        origin = _lookup_provenance(getattr(obj, "ddl_file", None), provenance)
        source_cell = f'<span class="mono" style="font-size:11px;color:#6C757D">{source_file}</span>'
        if origin and obj.state in (DeployState.FAILED, DeployState.SKIPPED):
            source_cell += (
                f'<div style="font-size:10px;color:#F47B20;margin-top:2px">'
                f"✎ {origin}</div>"
            )

        rows.append(
            f"<tr>"
            f'<td style="text-align:center;color:#6C757D">{i}</td>'
            f"{wave_cell}"
            f'<td class="mono">{_display_name(obj)}</td>'
            f"<td>{intent_html}{type_html}</td>"
            f"<td>{status_html}</td>"
            f"<td>{source_cell}</td>"
            f"<td>{'<br>'.join(details)}"
            f"{rollback_html}{extra_html}</td>"
            f"</tr>"
        )

        # Provenance drill-down — emit a second TR spanning all
        # columns when this object failed or was skipped AND we have
        # a chain for it. This is the only spot the report uses an
        # expandable detail; keeps the table dense for the happy
        # path while giving the DBA a one-click path into the full
        # transformation chain when something went wrong.
        if obj.state in (DeployState.FAILED, DeployState.SKIPPED):
            chain = _lookup_chain(getattr(obj, "ddl_file", None), provenance)
            if chain is not None:
                rows.append(
                    f"<tr>"
                    f'<td colspan="{drilldown_colspan}" '
                    f'style="background:{_LIGHT_BG};padding:8px 16px">'
                    f"{render_chain(chain)}"
                    f"</td>"
                    f"</tr>"
                )

    if not rows:
        # Check for noop re-run — all objects were completed in a prior
        # deployment and verified as still existing in the database.
        prior = getattr(result, "prior_completed", [])
        if prior:
            prior_count = len(prior)
            return (
                f"<h2>Object Results</h2>"
                f'<div class="no-actions">'
                f"All {prior_count} object{'s' if prior_count != 1 else ''} "
                f"were deployed in a previous run and verified as still "
                f"present in the database. Nothing new to deploy.</div>"
            )
        return '<h2>Object Results</h2><p style="color:#6C757D">No objects were processed.</p>'

    wave_header = '<th style="width:50px">Wave</th>' if has_waves else ""

    return f"""
<h2>Object Results</h2>
<table>
<thead><tr>
  <th style="width:40px">#</th>
  {wave_header}
  <th>Object</th>
  <th style="width:100px">Type</th>
  <th style="width:100px">Status</th>
  <th style="width:180px">Source</th>
  <th>Details</th>
</tr></thead>
<tbody>
{"".join(rows)}
</tbody>
</table>"""


def _html_footer(now):
    """Report footer."""
    return f"""
</div>
<div class="footer">
  Generated by ddl_deployer v2.0 &nbsp;|&nbsp; {now}
</div>
</body>
</html>"""
