"""
models.py — Data models for the Teradata Release Packager.

Defines the deployment phases, package metadata, build configuration,
and execution order for self-contained, environment-specific release
packages.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Dict, List


class DeployPhase(Enum):
    """
    Deployment phases in execution order.

    Each phase maps to a numbered directory in the package payload.
    The numbering enforces strict ordering: system objects must
    exist before databases, databases before grants, grants
    before DDL objects, objects before data.

    Phase semantics:
        SYSTEM          — CREATE MAP, CREATE ROLE, CREATE PROFILE,
                          CREATE AUTHORIZATION, CREATE FOREIGN SERVER.
                          System-level objects identical across
                          environments. No tokens. SKIP_IF_EXISTS.
        PRE_REQUISITES  — CREATE DATABASE, CREATE USER.
                          Foundation objects that contain everything else.
        DCL             — GRANT statements. Container-level permissions
                          that must exist before objects are created.
                          Three subdirectories, executed in order:
                            roles/    — GRANT ... TO {role}
                            users/    — GRANT ... TO {user}
                            inter_db/ — GRANT ... ON {database} TO {database}
                          Inter-database grants are auto-generated by
                          infer_grants.py from DDL intent analysis.
        DDL             — CREATE TABLE, CREATE VIEW, CREATE JOIN INDEX,
                          etc. The structural objects. All DDL uses CREATE;
                          the deployer owns idempotency via DROP+CREATE.
        DML             — Reference data loads (MERGE), seed data,
                          configuration inserts.
        POST_INSTALL    — Validation queries, statistics collection,
                          cleanup scripts, smoke tests.
    """

    SYSTEM = "00_system"
    PRE_REQUISITES = "01_pre_requisites"
    DCL = "02_dcl"
    DDL = "03_ddl"
    DML = "04_dml"
    POST_INSTALL = "05_post_install"


# -- Maps source directory names to deployment phases --
# The source project uses Paul's naming convention;
# the builder maps these to numbered phase directories.
SOURCE_DIR_MAP = {
    "system": DeployPhase.SYSTEM,
    "00_system": DeployPhase.SYSTEM,
    "pre-requisites": DeployPhase.PRE_REQUISITES,
    "pre_requisites": DeployPhase.PRE_REQUISITES,
    "DCL": DeployPhase.DCL,
    "dcl": DeployPhase.DCL,
    "DDL": DeployPhase.DDL,
    "ddl": DeployPhase.DDL,
    "DML": DeployPhase.DML,
    "dml": DeployPhase.DML,
    "post-install": DeployPhase.POST_INSTALL,
    "post_install": DeployPhase.POST_INSTALL,
}

# -- Sub-directory ordering within the SYSTEM phase --
# System-scope objects deploy in this sequence.
SYSTEM_SUBDIR_ORDER = {
    "maps": 0,
    "roles": 1,
    "profiles": 2,
    "authorizations": 3,
    "foreign_servers": 4,
}

# -- Sub-directory ordering within the DDL phase --
# Objects within DDL deploy in this sequence.
#
# JAR install scripts MUST come before procedures: PROCEDURE
# LANGUAGE JAVA bodies reference an installed JAR by alias via
# ``EXTERNAL NAME 'jar_alias:com.x.Foo.bar'``. CALL SQLJ.INSTALL_JAR
# is what registers that alias on the target. Deploying a Java
# procedure before its install script fails with "JAR not found".
#
# Functions follow procedures because Teradata FUNCTION can be
# LANGUAGE C (binary inlined via EXTERNAL NAME 'CS!path/...'),
# and the .c/.h companions are sibling files in functions/, not
# a separate jar_install path.
DDL_SUBDIR_ORDER = {
    "tables": 10,
    "join_indexes": 11,
    "hash_indexes": 11,
    "secondary_indexes": 12,
    "views": 20,
    "macros": 21,
    "jar_install": 22,
    "procedures": 23,
    "functions": 24,
    "script_table_operators": 25,
    "triggers": 30,
}

# -- Sub-directory ordering within the DCL phase --
# Each subdirectory contains a specific category of grant:
#   roles/    — GRANT privileges TO {role_name}
#              (e.g. GRANT SELECT ON database TO app_read_role)
#   users/    — GRANT privileges TO {user_name}
#              (e.g. GRANT SELECT ON database TO batch_user)
#   inter_db/ — GRANT privileges ON {database} TO {database}
#              (e.g. GRANT SELECT ON DOM_T TO DOM_V WITH GRANT OPTION)
#              These are auto-generated by infer_grants.py from DDL
#              intent analysis and validated by validate_grants.py.
# Execution order: roles first (0), then users (1), then inter-db (2).
DCL_SUBDIR_ORDER = {
    "roles": 0,
    "users": 1,
    "inter_db": 2,
}


@dataclass
class TokenDefinition:
    """
    A single token definition.

    Attributes:
        name:           Token name (without delimiters), e.g. 'STD_DATABASE'.
        description:    Human-readable description of what this token represents.
        required:       True if the token must be defined in properties.
        default_value:  Default value if not specified in properties.
        category:       Grouping for display (e.g. 'database', 'user', 'path').
    """

    name: str
    description: str = ""
    required: bool = True
    default_value: Optional[str] = None
    category: str = "general"


@dataclass
class BuildConfig:
    """
    Configuration for building a release package.

    Attributes:
        source_dir:       Root of the source project (containing payload/).
        environment:      Target environment name (e.g. 'DEV', 'TEST', 'PROD').
        package_name:     Logical package name (e.g. 'create_objects').
        build_number:     Incrementing build number (zero-padded 4 digits).
        env_config_file:  Path to the environment properties file.
        output_dir:       Where to write the package (default: current dir).
        archive_format:   'zip' or 'tar.gz'.
        author:           Builder's name/ID.
        description:      Free-text description of this release.
        source_commit:    Git commit hash (optional, for traceability).
    """

    source_dir: str
    environment: str
    package_name: str
    env_config_file: str
    build_number: Optional[int] = None
    output_dir: str = "."
    archive_format: str = "zip"
    author: str = ""
    description: str = ""
    source_commit: str = ""
    allow_dirty: bool = False
    # GAP-004: optional change management ticket reference.
    change_ref: Optional[str] = None


@dataclass
class BuildManifest:
    """
    Metadata stamped into the package at build time.

    Persisted as context/ships.build.json inside the package. Provides
    traceability from deployed objects back to the source and
    build process.

    Attributes:
        build_number:     Formatted build number (e.g. '0012').
        environment:      Target environment.
        package_name:     Logical package name.
        package_filename: Full archive filename.
        timestamp:        Build timestamp (ISO 8601).
        author:           Who built it.
        description:      Release description.
        source_commit:    Git commit hash.
        source_dirty:     True when the working tree had uncommitted changes
                          at build time (--allow-dirty was passed).
        token_count:      Number of tokens substituted.
        file_count:       Total files in the payload.
        phase_inventory:  Count of files per phase.
        tokens_resolved:  Dict of token_name → resolved_value.
        warnings:         Build-time warnings.
        release_group:    Shared identifier for paired packages
                          emitted by an auto-split build (Phase 2 of
                          the intra_package_dependency work). Empty
                          string for single-zip builds. Both halves
                          of an auto-split pair share the same
                          release_group, derived from the main zip's
                          basename so a DBA can grep for it across
                          the releases dir.
        role:             Marks this archive's role within an auto-
                          split pair. ``"prereqs"`` for the zip
                          containing CREATE DATABASE / CREATE USER
                          statements, ``"main"`` for the zip
                          containing dependants, ``""`` for single-
                          zip builds (no split occurred).
        requires:         Names of sibling archives that must be
                          deployed BEFORE this one. The main zip in
                          an auto-split pair lists the prereqs zip
                          here; the prereqs zip's list is empty.
                          Empty for single-zip builds.
        discovery:        Resolved discovery configuration stamped at
                          build time. Contains ``extensions`` — a
                          sorted list of all file extensions that were
                          in scope for harvest (defaults plus any
                          project-level additions from
                          ``ships.yaml``'s ``discovery.extensions``).
                          The embedded deployer reads this at startup
                          to drive its walk, eliminating the hard-coded
                          extension list and ensuring custom extensions
                          are honoured end-to-end.
        baseline_dir:     Shared filesystem path where the deployer
                          reads and writes schema drift baselines
                          (post-deploy SHOW captures).  Configured via
                          ``ships.yaml``'s ``deployment.baseline_dir``.
                          Empty string means drift detection is disabled.
        schema_version:   JSON schema version for context/ships.build.json.
    """

    build_number: str
    environment: str
    package_name: str
    package_filename: str
    timestamp: str
    author: str = ""
    description: str = ""
    source_commit: str = ""
    source_dirty: bool = False
    token_count: int = 0
    file_count: int = 0
    phase_inventory: Dict[str, int] = field(default_factory=dict)
    tokens_resolved: Dict[str, str] = field(default_factory=dict)
    warnings: List[str] = field(default_factory=list)
    release_group: str = ""
    role: str = ""
    requires: List[str] = field(default_factory=list)
    trust: Dict[str, object] = field(default_factory=dict)
    discovery: Dict[str, object] = field(default_factory=dict)
    baseline_dir: str = ""
    # Security: explicit target environment lock (GAP-002).
    # Set to the same value as ``environment`` at Package time so the
    # deployer can verify the operator has not aimed this package at
    # the wrong environment.
    target_env: str = ""
    # GAP-004: change management ticket reference.
    # Null when not supplied.  When the target environment has
    # require_change_ref: true in ships.yaml, Ship will fail if this
    # is absent or null.
    change_ref: Optional[str] = None
    # Whether the target environment requires a change reference.
    # Stamped from ships.yaml at Package time so the deployer can
    # enforce the policy without access to the project config.
    require_change_ref: bool = False
    # GAP-005: whether the target environment requires a package signature.
    # Stamped from ships.yaml environments.<ENV>.require_signature at
    # Package time.
    require_signature: bool = False
    # GAP-006: minimum number of approvals required for Ship.
    # 1 = self-certify (default, no approval code needed).
    # 2 = 4-eyes (a second operator must run 'ships approve').
    require_approvals: int = 1
    # GAP-015: whether TLS/SSL is required for the connection.
    # Stamped from ships.yaml environments.<ENV>.require_tls at Package time.
    require_tls: bool = False
    # GAP-012: explicit build timestamp for TTL/staleness checks.
    # Set to the same value as timestamp at Package time.
    package_built_at: str = ""
    # Maximum age in days before the package_age check fires.
    # 0 = disabled.  Default: 30.
    package_max_age_days: int = 30
    # 'warning' or 'error' — severity when the package exceeds max age.
    package_age_violation_level: str = "warning"
    # Option C: whether the target environment requires an Ed25519 asymmetric
    # signature sidecar.  Stamped from ships.yaml
    # environments.<ENV>.require_asymmetric_signature at Package time.
    require_asymmetric_signature: bool = False
    # Option C: Ed25519 public key PEM string, committed to the project repo.
    # Stamped from ships.yaml signing.public_key (if present) at Package time.
    # Allows DBAs to verify without needing a separate --public-key flag.
    ships_public_key: str = ""
    schema_version: str = "1.0"


@dataclass
class DeployConfig:
    """
    Configuration used at deployment time by the DBA.

    Read from the package's config/ directory and CLI arguments.

    Attributes:
        host:           Teradata host.
        user:           Teradata user.
        password:       Teradata password.
        logmech:        Logon mechanism (e.g. 'LDAP', 'TD2').
        dry_run:        Simulate without executing.
        continue_on_error: Continue past failures.
        query_band:     Additional query band key=value pairs.
    """

    host: str
    user: str
    password: str = ""
    logmech: str = ""
    dry_run: bool = False
    continue_on_error: bool = False
    query_band: Dict[str, str] = field(default_factory=dict)
