/*
** Implied grants for {{CallCentre_OBS_BUS_V}}
** Auto-generated by infer_grants.py from DDL intent analysis
** Source: SHIPS project callcentre
**
** Grantee: {{CallCentre_OBS_BUS_V}}
**
** Axiom: container-level grants derived from SQL verb
**         decomposition per referenced database.
**         Each referenced database receives only the
**         privilege matching the operation applied to
**         its objects.
**
** Contributing DDL files:
**   CallCentre_OBS_BUS_V.agent_outcome.viw (VIEW: agent_outcome)
**   CallCentre_OBS_BUS_V.change_event.viw (VIEW: change_event)
**   CallCentre_OBS_BUS_V.data_quality_metric.viw (VIEW: data_quality_metric)
**   CallCentre_OBS_BUS_V.lineage_run.viw (VIEW: lineage_run)
**   CallCentre_OBS_BUS_V.model_performance.viw (VIEW: model_performance)
*/

GRANT SELECT ON {{CallCentre_OBS_STD_V}} TO {{CallCentre_OBS_BUS_V}} WITH GRANT OPTION;
