/*
** Implied grants for {{CallCentre_PRE_STD_V}}
** Auto-generated by infer_grants.py from DDL intent analysis
** Source: SHIPS project callcentre
**
** Grantee: {{CallCentre_PRE_STD_V}}
**
** Axiom: container-level grants derived from SQL verb
**         decomposition per referenced database.
**         Each referenced database receives only the
**         privilege matching the operation applied to
**         its objects.
**
** Contributing DDL files:
**   CallCentre_PRE_STD_V.call_behaviour_features.viw (VIEW: call_behaviour_features)
**   CallCentre_PRE_STD_V.model_prediction.viw (VIEW: model_prediction)
*/

GRANT SELECT ON {{CallCentre_PRE_STD_T}} TO {{CallCentre_PRE_STD_V}} WITH GRANT OPTION;
