/*
** Implied grants for {{CallCentre_PRE_BUS_V}}
** Auto-generated by infer_grants.py from DDL intent analysis
** Source: SHIPS project callcentre
**
** Grantee: {{CallCentre_PRE_BUS_V}}
**
** Axiom: container-level grants derived from SQL verb
**         decomposition per referenced database.
**         Each referenced database receives only the
**         privilege matching the operation applied to
**         its objects.
**
** Contributing DDL files:
**   CallCentre_PRE_BUS_V.call_features_current.viw (VIEW: call_features_current)
**   CallCentre_PRE_BUS_V.call_features_enriched.viw (VIEW: call_features_enriched)
**   CallCentre_PRE_BUS_V.call_features_pit.viw (VIEW: call_features_pit)
**   CallCentre_PRE_BUS_V.model_prediction.viw (VIEW: model_prediction)
*/

GRANT SELECT ON {{CallCentre_DOM_BUS_V}} TO {{CallCentre_PRE_BUS_V}} WITH GRANT OPTION;
GRANT SELECT ON {{CallCentre_DOM_STD_V}} TO {{CallCentre_PRE_BUS_V}} WITH GRANT OPTION;
GRANT SELECT ON {{CallCentre_PRE_STD_V}} TO {{CallCentre_PRE_BUS_V}} WITH GRANT OPTION;
