/*
** Implied grants for {{CallCentre_SCH_BUS_V}}
** Auto-generated by infer_grants.py from DDL intent analysis
** Source: SHIPS project callcentre
**
** Grantee: {{CallCentre_SCH_BUS_V}}
**
** Axiom: container-level grants derived from SQL verb
**         decomposition per referenced database.
**         Each referenced database receives only the
**         privilege matching the operation applied to
**         its objects.
**
** Contributing DDL files:
**   CallCentre_SCH_BUS_V.call_embedding_ref.viw (VIEW: call_embedding_ref)
**   CallCentre_SCH_BUS_V.call_keywords.viw (VIEW: call_keywords)
**   CallCentre_SCH_BUS_V.call_searchable.viw (VIEW: call_searchable)
*/

GRANT SELECT ON {{CallCentre_DOM_BUS_V}} TO {{CallCentre_SCH_BUS_V}} WITH GRANT OPTION;
GRANT SELECT ON {{CallCentre_SCH_STD_V}} TO {{CallCentre_SCH_BUS_V}} WITH GRANT OPTION;
