/*
** Implied grants for {{CallCentre_DOM_STD_V}}
** Auto-generated by infer_grants.py from DDL intent analysis
** Source: SHIPS project callcentre
**
** Grantee: {{CallCentre_DOM_STD_V}}
**
** Axiom: container-level grants derived from SQL verb
**         decomposition per referenced database.
**         Each referenced database receives only the
**         privilege matching the operation applied to
**         its objects.
**
** Contributing DDL files:
**   CallCentre_DOM_STD_V.Agent_H.viw (VIEW: Agent_H)
**   CallCentre_DOM_STD_V.Call_Category_Score_H.viw (VIEW: Call_Category_Score_H)
**   CallCentre_DOM_STD_V.Call_Dynamics_H.viw (VIEW: Call_Dynamics_H)
**   CallCentre_DOM_STD_V.Call_H.viw (VIEW: Call_H)
**   CallCentre_DOM_STD_V.Call_Score_Cnt_H.viw (VIEW: Call_Score_Cnt_H)
**   CallCentre_DOM_STD_V.Call_Score_H.viw (VIEW: Call_Score_H)
**   CallCentre_DOM_STD_V.Call_Summary_H.viw (VIEW: Call_Summary_H)
**   CallCentre_DOM_STD_V.Call_Topic_H.viw (VIEW: Call_Topic_H)
*/

GRANT SELECT ON {{CallCentre_DOM_STD_T}} TO {{CallCentre_DOM_STD_V}} WITH GRANT OPTION;
