/*
** Implied grants for {{CallCentre_DOM_BUS_V}}
** Auto-generated by infer_grants.py from DDL intent analysis
** Source: SHIPS project callcentre
**
** Grantee: {{CallCentre_DOM_BUS_V}}
**
** Axiom: container-level grants derived from SQL verb
**         decomposition per referenced database.
**         Each referenced database receives only the
**         privilege matching the operation applied to
**         its objects.
**
** Contributing DDL files:
**   CallCentre_DOM_BUS_V.Agent_Current.viw (VIEW: Agent_Current)
**   CallCentre_DOM_BUS_V.Call_Category_Score_Current.viw (VIEW: Call_Category_Score_Current)
**   CallCentre_DOM_BUS_V.Call_Current.viw (VIEW: Call_Current)
**   CallCentre_DOM_BUS_V.Call_Dynamics_Current.viw (VIEW: Call_Dynamics_Current)
**   CallCentre_DOM_BUS_V.Call_Score_Cnt_Current.viw (VIEW: Call_Score_Cnt_Current)
**   CallCentre_DOM_BUS_V.Call_Score_Current.viw (VIEW: Call_Score_Current)
**   CallCentre_DOM_BUS_V.Call_Summary_Current.viw (VIEW: Call_Summary_Current)
**   CallCentre_DOM_BUS_V.Call_Topic_Current.viw (VIEW: Call_Topic_Current)
*/

GRANT SELECT ON {{CallCentre_DOM_STD_V}} TO {{CallCentre_DOM_BUS_V}} WITH GRANT OPTION;
