/*
** Implied grants for {{CallCentre_SCH_STD_V}}
** Auto-generated by infer_grants.py from DDL intent analysis
** Source: SHIPS project callcentre
**
** Grantee: {{CallCentre_SCH_STD_V}}
**
** Axiom: container-level grants derived from SQL verb
**         decomposition per referenced database.
**         Each referenced database receives only the
**         privilege matching the operation applied to
**         its objects.
**
** Contributing DDL files:
**   CallCentre_SCH_STD_V.call_embedding_ref.viw (VIEW: call_embedding_ref)
**   CallCentre_SCH_STD_V.call_keyword_token.viw (VIEW: call_keyword_token)
**   CallCentre_SCH_STD_V.call_searchable_text.viw (VIEW: call_searchable_text)
*/

GRANT SELECT ON {{CallCentre_SCH_STD_T}} TO {{CallCentre_SCH_STD_V}} WITH GRANT OPTION;
