/*
** Implied grants for {{CallCentre_SEM_BUS_V}}
** Auto-generated by infer_grants.py from DDL intent analysis
** Source: SHIPS project callcentre
**
** Grantee: {{CallCentre_SEM_BUS_V}}
**
** Axiom: container-level grants derived from SQL verb
**         decomposition per referenced database.
**         Each referenced database receives only the
**         privilege matching the operation applied to
**         its objects.
**
** Contributing DDL files:
**   CallCentre_SEM_BUS_V.column_catalogue.viw (VIEW: column_catalogue)
**   CallCentre_SEM_BUS_V.column_metadata.viw (VIEW: column_metadata)
**   CallCentre_SEM_BUS_V.data_lineage.viw (VIEW: data_lineage)
**   CallCentre_SEM_BUS_V.data_product_manifest.viw (VIEW: data_product_manifest)
**   CallCentre_SEM_BUS_V.data_product_map.viw (VIEW: data_product_map)
**   CallCentre_SEM_BUS_V.data_product_map_primary_objects.viw (VIEW: data_product_map_primary_objects)
**   CallCentre_SEM_BUS_V.data_product_object_catalog.viw (VIEW: data_product_object_catalog)
**   CallCentre_SEM_BUS_V.data_product_orientation.viw (VIEW: data_product_orientation)
**   CallCentre_SEM_BUS_V.entity_metadata.viw (VIEW: entity_metadata)
**   CallCentre_SEM_BUS_V.lineage_graph.viw (VIEW: lineage_graph)
**   CallCentre_SEM_BUS_V.lineage_run_latest.viw (VIEW: lineage_run_latest)
**   CallCentre_SEM_BUS_V.naming_standard.viw (VIEW: naming_standard)
**   CallCentre_SEM_BUS_V.relationship_paths.viw (VIEW: relationship_paths)
**   CallCentre_SEM_BUS_V.table_relationship.viw (VIEW: table_relationship)
**   CallCentre_SEM_BUS_V.trust_engine_latest.viw (VIEW: trust_engine_latest)
**   CallCentre_SEM_BUS_V.view_metadata.viw (VIEW: view_metadata)
*/

GRANT SELECT ON {{CallCentre_OBS_STD_V}} TO {{CallCentre_SEM_BUS_V}} WITH GRANT OPTION;
GRANT SELECT ON {{CallCentre_SEM_STD_V}} TO {{CallCentre_SEM_BUS_V}} WITH GRANT OPTION;
GRANT SELECT ON {{DataProductsMaster_GOV_BUS_V}} TO {{CallCentre_SEM_BUS_V}} WITH GRANT OPTION;
