/*
** Implied grants for {{CallCentre_MEM_BUS_V}}
** Auto-generated by infer_grants.py from DDL intent analysis
** Source: SHIPS project callcentre
**
** Grantee: {{CallCentre_MEM_BUS_V}}
**
** Axiom: container-level grants derived from SQL verb
**         decomposition per referenced database.
**         Each referenced database receives only the
**         privilege matching the operation applied to
**         its objects.
**
** Contributing DDL files:
**   CallCentre_MEM_BUS_V.Business_Glossary.viw (VIEW: Business_Glossary)
**   CallCentre_MEM_BUS_V.Change_Log.viw (VIEW: Change_Log)
**   CallCentre_MEM_BUS_V.Cookbook_Active.viw (VIEW: Cookbook_Active)
**   CallCentre_MEM_BUS_V.Current_Decisions.viw (VIEW: Current_Decisions)
**   CallCentre_MEM_BUS_V.Design_Decision.viw (VIEW: Design_Decision)
**   CallCentre_MEM_BUS_V.Glossary_Active.viw (VIEW: Glossary_Active)
**   CallCentre_MEM_BUS_V.Implementation_Note.viw (VIEW: Implementation_Note)
**   CallCentre_MEM_BUS_V.Module_Registry.viw (VIEW: Module_Registry)
**   CallCentre_MEM_BUS_V.Module_Registry_Current.viw (VIEW: Module_Registry_Current)
**   CallCentre_MEM_BUS_V.Query_Cookbook.viw (VIEW: Query_Cookbook)
**   CallCentre_MEM_BUS_V.active_sessions.viw (VIEW: active_sessions)
**   CallCentre_MEM_BUS_V.agent_interaction.viw (VIEW: agent_interaction)
**   CallCentre_MEM_BUS_V.agent_session.viw (VIEW: agent_session)
**   CallCentre_MEM_BUS_V.discovered_pattern.viw (VIEW: discovered_pattern)
**   CallCentre_MEM_BUS_V.learned_strategies_org.viw (VIEW: learned_strategies_org)
**   CallCentre_MEM_BUS_V.learned_strategy.viw (VIEW: learned_strategy)
*/

GRANT SELECT ON {{CallCentre_MEM_STD_V}} TO {{CallCentre_MEM_BUS_V}} WITH GRANT OPTION;
