/*
** Implied grants for {{CallCentre_SEM_STD_V}}
** Auto-generated by infer_grants.py from DDL intent analysis
** Source: SHIPS project callcentre
**
** Grantee: {{CallCentre_SEM_STD_V}}
**
** Axiom: container-level grants derived from SQL verb
**         decomposition per referenced database.
**         Each referenced database receives only the
**         privilege matching the operation applied to
**         its objects.
**
** Contributing DDL files:
**   CallCentre_SEM_STD_V.column_metadata.viw (VIEW: column_metadata)
**   CallCentre_SEM_STD_V.data_lineage.viw (VIEW: data_lineage)
**   CallCentre_SEM_STD_V.data_product_map.viw (VIEW: data_product_map)
**   CallCentre_SEM_STD_V.data_product_map_primary_objects.viw (VIEW: data_product_map_primary_objects)
**   CallCentre_SEM_STD_V.entity_metadata.viw (VIEW: entity_metadata)
**   CallCentre_SEM_STD_V.naming_standard.viw (VIEW: naming_standard)
**   CallCentre_SEM_STD_V.table_relationship.viw (VIEW: table_relationship)
**   CallCentre_SEM_STD_V.trust_engine_run.viw (VIEW: trust_engine_run)
**   CallCentre_SEM_STD_V.view_column_type.viw (VIEW: view_column_type)
**   CallCentre_SEM_STD_V.view_metadata.viw (VIEW: view_metadata)
*/

GRANT SELECT ON {{CallCentre_SEM_STD_T}} TO {{CallCentre_SEM_STD_V}} WITH GRANT OPTION;
